// audio.c
#include <string.h>
#include "os.h"
#include "voxen.h"
#include "./External/miniaudio.h"

#define MAX_CHANNELS 16
#define MAX_AMBIENT_NOISES 128
ma_engine audio_engine;
ma_sound mp3_sounds[2]; // For crossfading
int32_t mp3_slot = 0;
ma_sound wav_sounds[MAX_CHANNELS];
float wav_volumes[MAX_CHANNELS]; // Setting independent base sfx volume (e.g. dropped physics object hard or lightly volume, independent of position).
int32_t wav_count = 0;
ma_sound log_sound;
// Usage: play_wav("./Audio/cyborgs/yourlevelsareterrible.wav",0.1f); WORKED!

void InitializeAudio(void) {
    ma_result result;
    ma_engine_config engine_config = ma_engine_config_init();
    engine_config.channels = 2; // Stereo output, adjust if needed
    result = ma_engine_init(&engine_config, &audio_engine);
    if (result != MA_SUCCESS) { DualLog("ERROR: Failed to initialize miniaudio engine: %d\n", result); return; }
}

void mp3_clear(void) {
    ma_sound_stop(&mp3_sounds[0]);
    ma_sound_stop(&mp3_sounds[1]);
    mp3_slot = 0;
}

float GetSFXVolume(float volume) { return ((float)Sys_Settings.VolumeMaster/100.0f) * ((float)Sys_Settings.VolumeEffects/100.0f) * volume; }
float GetMusicVolume(void) { return ((float)Sys_Settings.VolumeMaster/100.0f) * ((float)Sys_Settings.VolumeMusic/100.0f); }
float GetMessageVolume(void) { return ((float)Sys_Settings.VolumeMaster/100.0f) * ((float)Sys_Settings.VolumeMessage/100.0f); }
void set_music_volume(void) { for (int i=0;i<2;++i) { ma_sound_set_volume(&mp3_sounds[i], GetMusicVolume()); } }
void set_sfx_volume(void) { for (int i=0;i<MAX_CHANNELS;++i) { ma_sound_set_volume(&wav_sounds[i], GetSFXVolume(wav_volumes[i])); } }
void set_message_volume(void) { ma_sound_set_volume(&log_sound, GetMessageVolume()); }
void set_master_volume(void) { set_sfx_volume(); set_music_volume(); set_message_volume(); }

void play_mp3(const char* path, int32_t fade_in_ms) {
    ma_sound_uninit(&mp3_sounds[mp3_slot]);
    ma_result result = ma_sound_init_from_file(&audio_engine, path, MA_SOUND_FLAG_STREAM, NULL, NULL, &mp3_sounds[mp3_slot]);
    if (result != MA_SUCCESS) { DualLog("ERROR: Failed to load MP3 %s: %d\n", path, result);  return; }
    
    float vol = GetMusicVolume();
    ma_sound_set_fade_in_milliseconds(&mp3_sounds[mp3_slot], 0.0f, vol, fade_in_ms);
    ma_sound_start(&mp3_sounds[mp3_slot]);
    ma_sound_set_volume(&mp3_sounds[mp3_slot], vol);
    mp3_slot = mp3_slot ? 0 : 1; // Toggle for crossfade
}

void play_wav(const char* path, float volume, Vector3 pos, bool positional) {
    int32_t slot = -1;
    for (int32_t i = 0; i < wav_count; i++) { // Try to find a free slot (either unused or finished)
        if (!ma_sound_is_playing(&wav_sounds[i]) && ma_sound_at_end(&wav_sounds[i])) {
            ma_sound_uninit(&wav_sounds[i]);
            slot = i;
            break;
        }
    }

    if (slot == -1 && wav_count < MAX_CHANNELS) slot = wav_count++; // If no free slot, use a new one if available
    if (slot == -1) { DualLog("WARNING: Max effect WAV channels (%d) reached\n", MAX_CHANNELS); return; }

    ma_result result = ma_sound_init_from_file(&audio_engine, path, 0, NULL, NULL, &wav_sounds[slot]);
    if (result != MA_SUCCESS) {
        DualLog("ERROR: Failed to load effect WAV %s: %d\n", path, result);
        if (slot == wav_count - 1) wav_count--; // Revert count if init fails
        return;
    }
    
    if (positional) ma_sound_set_position(&wav_sounds[slot], pos.x, pos.y, pos.z);
    ma_sound_set_spatialization_enabled(&wav_sounds[slot], (ma_bool32)positional);
    wav_volumes[slot] = volume;
    ma_sound_set_volume(&wav_sounds[slot], GetSFXVolume(wav_volumes[slot]));
    ma_sound_start(&wav_sounds[slot]);
}

void play_message(const char* path) {
    if (ma_sound_is_playing(&log_sound)) { ma_sound_stop(&log_sound); ma_sound_uninit(&log_sound); }
    ma_result result = ma_sound_init_from_file(&audio_engine, path, 0, NULL, NULL, &log_sound);
    if (result != MA_SUCCESS) { DualLog("ERROR: Failed to load message WAV %s: %d\n", path, result); return; }
    
    ma_sound_set_spatialization_enabled(&log_sound, false);
    ma_sound_set_volume(&log_sound, GetMessageVolume());
    ma_sound_start(&log_sound);
}

// ============================================================================
uint16_t loadedAmbients = 0;
uint16_t ambientRegistry[MAX_AMBIENT_NOISES]; // For ambient_ type entities that play looped sound

typedef struct {
    uint16_t    index;
    const char* filename;          // ./Audio/ambient/…
} AmbientDef;

static const AmbientDef g_ambient_defs[] = {
    {621, "airhiss.wav"},          {622, "clicker.wav"},
    {623, "compressor.wav"},       {624, "dishwasher.wav"},
    {625, "drip_amb.wav"},         {626, "fan1.wav"},
    {627, "generator_gas.wav"},    {628, "gurgle.wav"},
    {629, "icemaker.wav"},         {630, "intake.wav"},
    {631, "lathe.wav"},            {632, "lev3loop1.wav"},
    {633, "lev3loop2.wav"},        {634, "lev3loop3.wav"},
    {635, "lev3loop4.wav"},        {636, "liquid_bubble.wav"},
    {637, "lava2.wav"},            {638, "rain.wav"},
    {639, "machgear_loop.wav"},    {640, "machine_ambience.wav"},
    {641, "machine_go.wav"},       {642, "machine_humamb7.wav"},
    {643, "machine_humlonoise.wav"},{644, "machine_loop1.wav"},
    {645, "machine_loop2.wav"},    {646, "machinea1.wav"},
    {647, "machinevat_loop.wav"},  {648, "mist.wav"},
    {649, "pipewater_loop.wav"},   {650, "powerloom.wav"},
    {651, "pump.wav"},             {652, "pump2.wav"},
    {653, "rain.wav"},             {654, "steam_loop.wav"},
    {655, "washing_machine.wav"},
};
#define AMBIENT_DEF_COUNT  (sizeof(g_ambient_defs)/sizeof(g_ambient_defs[0]))

typedef struct {
    ma_sound  sound;
    ma_bool32 loaded;
    float     length_sec;
} AmbientSlot;

static AmbientSlot ambientSlots[AMBIENT_DEF_COUNT] = {0};

static float ma_sound_get_length_sec(ma_sound* pSound) {
    if (!pSound) return 0.0f;
    
    ma_uint64 frames;
    if (ma_sound_get_length_in_pcm_frames(pSound, &frames) != MA_SUCCESS) return 0.0f;
    
    ma_uint32 sr = ma_engine_get_sample_rate(ma_sound_get_engine(pSound));
    return (sr == 0) ? 0.0f : (float)frames / (float)sr;
}

static const AmbientDef* ambient_def_by_index(uint16_t idx) {
    for (size_t i = 0; i < AMBIENT_DEF_COUNT; ++i) {
        if (g_ambient_defs[i].index == idx) return &g_ambient_defs[i];
    }
    
    return NULL;
}

void UpdateAmbientSounds(void) {
    const Vector3* player = &instances[PLAYER1].position;
    const float max_range = 7.68f;
    const float max_range_sq = max_range * max_range;
    for (uint16_t i = 0; i < loadedAmbients; ++i) {
        const uint16_t ent_idx = ambientRegistry[i];
        const Entity* ent = &instances[ent_idx];
        const AmbientDef* def = ambient_def_by_index(ent->index);
        if (!def) { DualLogError("  [SKIP] Entity %u has unknown index %u\n", ent_idx, ent->index); continue; }

        const float dist_sq = squareDistance3D(player->x, player->y, player->z, ent->position.x, ent->position.y, ent->position.z);
        const float distance = vsqrtf(dist_sq);
        bool in_range = (dist_sq < max_range_sq);
        int32_t subIdx = PosGetCellCoords(ent->position.x, ent->position.z);
        int cellIdx = (playerCellIdx * ARRSIZE);
        int flat_idx = cellIdx + subIdx;
        if (!get_cull_bit(precomputedVisibleCellsFromHere,flat_idx)) in_range = false;
        const size_t slot_idx = (size_t)(def - g_ambient_defs);
        AmbientSlot* slot = &ambientSlots[slot_idx];
        if (in_range) {
            if (!slot->loaded) {
                char path[512];
                snprintf(path, sizeof(path), "./Audio/ambient/%s", def->filename);
                ma_sound_uninit(&slot->sound);
                ma_result r = ma_sound_init_from_file(&audio_engine, path, MA_SOUND_FLAG_DECODE | MA_SOUND_FLAG_NO_SPATIALIZATION, NULL, NULL, &slot->sound);
                if (r != MA_SUCCESS) continue;

                slot->length_sec = ma_sound_get_length_sec(&slot->sound);
                if (slot->length_sec <= 0.0f) { ma_sound_uninit(&slot->sound); continue; }

                ma_sound_set_looping(&slot->sound, MA_TRUE);
                slot->loaded = MA_TRUE;
            }

            if (!ma_sound_is_playing(&slot->sound)) ma_sound_start(&slot->sound);

            // Time sync
            if (slot->length_sec > 0.0f) {
                ma_uint64 cur;
                ma_sound_get_cursor_in_pcm_frames(&slot->sound, &cur);
            }

            // Volume
            float vol_factor = (distance <= 1.0f) ? 1.0f
                               : (distance >= max_range) ? 0.0f
                                 : (max_range - distance) / (max_range - 1.0f);
                                 
            float final_vol = ent->volume * vol_factor;
            ma_sound_set_volume(&slot->sound, final_vol);
        } else {
            if (ma_sound_is_playing(&slot->sound)) ma_sound_stop(&slot->sound);
        }
    }
}

void ResetLevelAudio(void) {
    loadedAmbients = 0;
    memset(ambientRegistry, 0, loadedAmbients * sizeof(uint16_t));
    for (uint16_t i = START_INDEX_LEVEL_INSTANCES; i<loadedInstances;++i) {
        uint16_t entIdx = instances[i].index;
        if (ConstIndexIsAmbient(entIdx)) {
            ambientRegistry[loadedAmbients] = i;
            loadedAmbients++;
            if (loadedAmbients >= MAX_AMBIENT_NOISES) { DualLogError("%u exceeded max number of ambient noises %u!\n",loadedAmbients,MAX_AMBIENT_NOISES); OS_Exit(1); }
            
            instances[i].volume = entities[entIdx].volume * 0.5f;
        }
    }
}

const char* sounds[SOUNDS_COUNT] = {
    "./Audio/misc/null.wav",
    "./Audio/ambient/ambient_frogs.wav",
    "./Audio/ambient/clicker.wav",
    "./Audio/ambient/compressor.wav",
    "./Audio/ambient/dishwasher.wav",
    "./Audio/ambient/drip_amb.wav",
    "./Audio/ambient/fan1.wav",
    "./Audio/ambient/generator_gas.wav",
    "./Audio/ambient/gurgle.wav",
    "./Audio/ambient/icemaker.wav",
    "./Audio/ambient/ind_lift1.wav",
    "./Audio/ambient/ind_lift2.wav",
    "./Audio/ambient/intake.wav",
    "./Audio/ambient/lathe.wav",
    "./Audio/ambient/lava2.wav",
    "./Audio/ambient/lev3loop1.wav",
    "./Audio/ambient/lev3loop2.wav",
    "./Audio/ambient/lev3loop3.wav",
    "./Audio/ambient/lev3loop4.wav",
    "./Audio/ambient/liquid_bubble.wav",
    "./Audio/ambient/machgear_loop.wav",
    "./Audio/ambient/machine_ambience.wav",
    "./Audio/ambient/machine_go.wav",
    "./Audio/ambient/machine_humamb7.wav",
    "./Audio/ambient/machine_humlonoise.wav",
    "./Audio/ambient/machine_loop1.wav",
    "./Audio/ambient/machine_loop2.wav",
    "./Audio/ambient/machinea1.wav",
    "./Audio/ambient/machinevat_loop.wav",
    "./Audio/ambient/pipewater_loop.wav",
    "./Audio/ambient/powerloom.wav",
    "./Audio/ambient/pump.wav",
    "./Audio/ambient/pump2.wav",
    "./Audio/ambient/rain.wav",
    "./Audio/ambient/sparks1.wav",
    "./Audio/ambient/sparks2.wav",
    "./Audio/ambient/sparks3.wav",
    "./Audio/ambient/steam_loop.wav",
    "./Audio/ambient/washing_machine.wav",
    "./Audio/buttons/button_beep.wav",
    "./Audio/buttons/button_chonk.wav",
    "./Audio/buttons/button_chuck.wav",
    "./Audio/buttons/button_clickclocktuck.wav",
    "./Audio/buttons/button_deny.wav",
    "./Audio/buttons/button_lswitch.wav",
    "./Audio/buttons/button_swipe.wav",
    "./Audio/buttons/keycard_success.wav",
    "./Audio/cyborgs/cyborg_die.wav",
    "./Audio/cyborgs/cyborg_die2.wav",
    "./Audio/cyborgs/cyborg_idle2.wav",
    "./Audio/cyborgs/cyborg_shoot.wav",
    "./Audio/cyborgs/cyborgwarrior_die.wav",
    "./Audio/cyborgs/diego_blubber.wav",
    "./Audio/cyborgs/ediego_dontkeepmewaiting.wav",
    "./Audio/cyborgs/ediego_faceme.wav",
    "./Audio/cyborgs/ediego_facexecutioner.wav",
    "./Audio/cyborgs/ediego_finishexecution.wav",
    "./Audio/cyborgs/ediego_wewillmeetagain.wav",
    "./Audio/cyborgs/yourlevelsareterrible.wav",
    "./Audio/cyborgs/yourweaponsareshoddybadweapons.wav",
    "./Audio/destroy/attack1_explode.wav",
    "./Audio/destroy/camera_destroy.wav",
    "./Audio/destroy/crate_break.wav",
    "./Audio/destroy/explode_minor.wav",
    "./Audio/destroy/explosion1.wav",
    "./Audio/destroy/explosion2.wav",
    "./Audio/destroy/explosion3.wav",
    "./Audio/destroy/hit2.wav",
    "./Audio/destroy/hit3.wav",
    "./Audio/destroy/screen_destroy.wav",
    "./Audio/doors/door_platform.wav",
    "./Audio/doors/doorbulkhead_open.wav",
    "./Audio/doors/doorbulkhead_open2.wav",
    "./Audio/doors/doorcompartment_open.wav",
    "./Audio/doors/doormech_open.wav",
    "./Audio/doors/doorpnuematic_open.wav",
    "./Audio/doors/doorwall_move.wav",
    "./Audio/doors/doorwall_stop.wav",
    "./Audio/hud/activate.wav",
    "./Audio/hud/batteryuse.wav",
    "./Audio/hud/changeweapon.wav",
    "./Audio/hud/cyber.wav",
    "./Audio/hud/deactivate.wav",
    "./Audio/hud/emailalert.wav",
    "./Audio/hud/energy_gone.wav",
    "./Audio/hud/envirosuit_on.wav",
    "./Audio/hud/frob_hardware.wav",
    "./Audio/hud/frob_item.wav",
    "./Audio/hud/jumpjets_off.wav",
    "./Audio/hud/patchuse.wav",
    "./Audio/hud/radiation.wav",
    "./Audio/hud/searchsound.wav",
    "./Audio/hud/select.wav",
    "./Audio/hud/sensaround.wav",
    "./Audio/hud/shield_absorb.wav",
    "./Audio/hud/shield_off.wav",
    "./Audio/hud/shield_on.wav",
    "./Audio/hud/tab.wav",
    "./Audio/hud/targetacquire.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/misc/chargingstation.wav",
    "./Audio/misc/energy_hum.wav",
    "./Audio/misc/forcebridge.wav",
    "./Audio/misc/healstation.wav",
    "./Audio/misc/klaxon_station_alarm.wav",
    "./Audio/misc/machine_on.wav",
    "./Audio/misc/teleport.wav",
    "./Audio/misc/wing-o.wav",
    "./Audio/mutants/avianmut_attack.wav",
    "./Audio/mutants/avianmut_die.wav",
    "./Audio/mutants/avianmut_die2.wav",
    "./Audio/mutants/avianmut_sightsound.wav",
    "./Audio/mutants/footstep1.wav",
    "./Audio/mutants/footstep2.wav",
    "./Audio/mutants/footstep3.wav",
    "./Audio/mutants/footstep4.wav",
    "./Audio/mutants/footstep5.wav",
    "./Audio/mutants/gortiger_die.wav",
    "./Audio/mutants/gortiger_idle1.wav",
    "./Audio/mutants/gortiger_sightsound.wav",
    "./Audio/mutants/invisiblemut_die.wav",
    "./Audio/mutants/invisiblemut_idle1.wav",
    "./Audio/mutants/mutant_attack.wav",
    "./Audio/mutants/mutant_die.wav",
    "./Audio/mutants/plantmut_die2.wav",
    "./Audio/mutants/plantmut_throw.wav",
    "./Audio/mutants/plantmutstep1.wav",
    "./Audio/mutants/plantmutstep2.wav",
    "./Audio/mutants/plantmutstep3.wav",
    "./Audio/mutants/steplarge1.wav",
    "./Audio/mutants/steplarge2.wav",
    "./Audio/mutants/steplarge3.wav",
    "./Audio/mutants/steplarge4.wav",
    "./Audio/mutants/steplarge5.wav",
    "./Audio/mutants/virusmut_die.wav",
    "./Audio/player/jump.wav",
    "./Audio/player/jumpland.wav",
    "./Audio/player/ladder.wav",
    "./Audio/player/painalarm.wav",
    "./Audio/player/painalarmfast.wav",
    "./Audio/player/playerpain1.wav",
    "./Audio/robots/bot_destroy1.wav",
    "./Audio/robots/bot_destroy2.wav",
    "./Audio/robots/bot_destroy3.wav",
    "./Audio/robots/bot_destroy4.wav",
    "./Audio/robots/bot_destroybig.wav",
    "./Audio/robots/bot_pincherattack.wav",
    "./Audio/robots/bot_shoot1.wav",
    "./Audio/robots/bot_shoot2.wav",
    "./Audio/robots/bot_shoot3.wav",
    "./Audio/robots/bot_sight1.wav",
    "./Audio/robots/bot_sight2.wav",
    "./Audio/robots/bot_sight3.wav",
    "./Audio/robots/footfall.wav",
    "./Audio/robots/footstep1.wav",
    "./Audio/robots/footstep2.wav",
    "./Audio/robots/footstep3.wav",
    "./Audio/robots/footstephuge1.wav",
    "./Audio/robots/footstephuge2.wav",
    "./Audio/robots/footstephuge3.wav",
    "./Audio/robots/footstepsmall1.wav",
    "./Audio/robots/footstepsmall2.wav",
    "./Audio/robots/hopper_die.wav",
    "./Audio/robots/servo.wav",
    "./Audio/vox/vox_abortingprogram.wav",
    "./Audio/vox/vox_accesspanellocked.wav",
    "./Audio/vox/vox_accesspanelunlocked.wav",
    "./Audio/vox/vox_armoryaccessoverriden.wav",
    "./Audio/vox/vox_armoryaccessreinstituted.wav",
    "./Audio/vox/vox_baydoor3locked.wav",
    "./Audio/vox/vox_betagrovejettisoned.wav",
    "./Audio/vox/vox_betagrovelvatrunlocked.wav",
    "./Audio/vox/vox_biocontaminantdetected.wav",
    "./Audio/vox/vox_blastdoorlocked.wav",
    "./Audio/vox/vox_blastdoorunlocked.wav",
    "./Audio/vox/vox_bridgesepdone.wav",
    "./Audio/vox/vox_bridgesepsoon.wav",
    "./Audio/vox/vox_bridgesepstage1.wav",
    "./Audio/vox/vox_bridgesepstage2.wav",
    "./Audio/vox/vox_cameractivsecdoor.wav",
    "./Audio/vox/vox_chargeraccessgranted.wav",
    "./Audio/vox/vox_chargeroff.wav",
    "./Audio/vox/vox_corelocksdisengaged.wav",
    "./Audio/vox/vox_cybconvcancelled.wav",
    "./Audio/vox/vox_cybconvenabled.wav",
    "./Audio/vox/vox_demodsuccess.wav",
    "./Audio/vox/vox_destructcancelled.wav",
    "./Audio/vox/vox_destructnotenabled.wav",
    "./Audio/vox/vox_destructsecaccess.wav",
    "./Audio/vox/vox_doorclosedisabled.wav",
    "./Audio/vox/vox_ediegostorageclosetunlocked.wav",
    "./Audio/vox/vox_elevatordisabled.wav",
    "./Audio/vox/vox_emeraccesslocked.wav",
    "./Audio/vox/vox_entercode.wav",
    "./Audio/vox/vox_fallingairpressure.wav",
    "./Audio/vox/vox_flightbayarmoryunlocked.wav",
    "./Audio/vox/vox_forcedoor1opened.wav",
    "./Audio/vox/vox_forcedoor2opened.wav",
    "./Audio/vox/vox_forcedoor3opened.wav",
    "./Audio/vox/vox_gammajettisoned.wav",
    "./Audio/vox/vox_grovejettisoned.wav",
    "./Audio/vox/vox_grovejettisonstage1.wav",
    "./Audio/vox/vox_groveunlocked.wav",
    "./Audio/vox/vox_hallaccess.wav",
    "./Audio/vox/vox_hospitalsecdoorsopened.wav",
    "./Audio/vox/vox_jettisonalreadyenabled.wav",
    "./Audio/vox/vox_jettisonenabled.wav",
    "./Audio/vox/vox_jettisonfailure.wav",
    "./Audio/vox/vox_lifepodcancelled.wav",
    "./Audio/vox/vox_lifepodlaunchstart.wav",
    "./Audio/vox/vox_lifepodsdisabled.wav",
    "./Audio/vox/vox_maintdoorlocked.wav",
    "./Audio/vox/vox_needisotope.wav",
    "./Audio/vox/vox_nomasterjettisonenabled.wav",
    "./Audio/vox/vox_nosecaccess.wav",
    "./Audio/vox/vox_powerdivertedtor.wav",
    "./Audio/vox/vox_programinstalled.wav",
    "./Audio/vox/vox_radiationshielddeacticated.wav",
    "./Audio/vox/vox_radiationtreatdone.wav",
    "./Audio/vox/vox_reactorcountdown.wav",
    "./Audio/vox/vox_reactoroveloadstart.wav",
    "./Audio/vox/vox_reactoroverloadaccess.wav",
    "./Audio/vox/vox_reactoroverloadbypassed.wav",
    "./Audio/vox/vox_receptacleisolinearchipset.wav",
    "./Audio/vox/vox_relay428failure.wav",
    "./Audio/vox/vox_relay428faulty.wav",
    "./Audio/vox/vox_relayfixed.wav",
    "./Audio/vox/vox_replacedemodulator.wav",
    "./Audio/vox/vox_robotprodcancelled.wav",
    "./Audio/vox/vox_robotsactivated.wav",
    "./Audio/vox/vox_safetyinterlockdisabled.wav",
    "./Audio/vox/vox_safetyinterlockengaged.wav",
    "./Audio/vox/vox_safetyinterlocksenabled.wav",
    "./Audio/vox/vox_safetyoverridesonolaser.wav",
    "./Audio/vox/vox_secompoverrideneeded.wav",
    "./Audio/vox/vox_shieldgeneratorsready.wav",
    "./Audio/vox/vox_shieldson.wav",
    "./Audio/vox/vox_thelaserisdestroyed.wav",
    "./Audio/weapons/noammo.wav",
    "./Audio/weapons/wblaster.wav",
    "./Audio/weapons/wdartgun.wav",
    "./Audio/weapons/wdrill.wav",
    "./Audio/weapons/wearthshake.wav",
    "./Audio/weapons/wflechette.wav",
    "./Audio/weapons/wgrenade_arm.wav",
    "./Audio/weapons/wion.wav",
    "./Audio/weapons/wlaserrapier_hit.wav",
    "./Audio/weapons/wlaserrapier_swing.wav",
    "./Audio/weapons/wlocknload.wav",
    "./Audio/weapons/wmagnum.wav",
    "./Audio/weapons/wmagpulse.wav",
    "./Audio/weapons/wmarksman.wav",
    "./Audio/weapons/wpipe_dmg.wav",
    "./Audio/weapons/wpipe_hit.wav",
    "./Audio/weapons/wpipe_swing.wav",
    "./Audio/weapons/wpistol.wav",
    "./Audio/weapons/wpistolsilenced.wav",
    "./Audio/weapons/wplasma.wav",
    "./Audio/weapons/wpulser.wav",
    "./Audio/weapons/wrailgun.wav",
    "./Audio/weapons/wreload.wav",
    "./Audio/weapons/wricoshet.wav",
    "./Audio/weapons/wriotgun.wav",
    "./Audio/weapons/wskorpion.wav",
    "./Audio/weapons/wsparq.wav",
    "./Audio/weapons/wstungun.wav",
    "./Audio/weapons/wwoosh.wav",
    "./Audio/ambient/airhiss.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step1.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step2.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step3.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step4.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step5.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step6.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step7.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step8.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step1.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step2.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step3.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step4.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step5.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step6.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step7.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step8.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step1.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step2.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step3.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step4.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step5.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step6.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step7.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step8.wav",
    "./Audio/physics/footsteps/Earth/earth_step1.wav",
    "./Audio/physics/footsteps/Earth/earth_step2.wav",
    "./Audio/physics/footsteps/Earth/earth_step3.wav",
    "./Audio/physics/footsteps/Earth/earth_step4.wav",
    "./Audio/physics/footsteps/Earth/earth_step5.wav",
    "./Audio/physics/footsteps/Earth/earth_step6.wav",
    "./Audio/physics/footsteps/Earth/earth_step7.wav",
    "./Audio/physics/footsteps/Earth/earth_step8.wav",
    "./Audio/physics/footsteps/Earth/gravel_step1.wav",
    "./Audio/physics/footsteps/Earth/gravel_step2.wav",
    "./Audio/physics/footsteps/Earth/gravel_step3.wav",
    "./Audio/physics/footsteps/Earth/gravel_step4.wav",
    "./Audio/physics/footsteps/Earth/gravel_step5.wav",
    "./Audio/physics/footsteps/Earth/gravel_step6.wav",
    "./Audio/physics/footsteps/Earth/gravel_step7.wav",
    "./Audio/physics/footsteps/Earth/gravel_step8.wav",
    "./Audio/physics/footsteps/Earth/rock_step1.wav",
    "./Audio/physics/footsteps/Earth/rock_step2.wav",
    "./Audio/physics/footsteps/Earth/rock_step3.wav",
    "./Audio/physics/footsteps/Earth/rock_step4.wav",
    "./Audio/physics/footsteps/Earth/rock_step5.wav",
    "./Audio/physics/footsteps/Earth/rock_step6.wav",
    "./Audio/physics/footsteps/Earth/rock_step7.wav",
    "./Audio/physics/footsteps/Earth/rock_step8.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step1.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step2.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step3.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step4.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step5.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step6.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step7.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step8.wav",
    "./Audio/physics/footsteps/Marble/marble_step1.wav",
    "./Audio/physics/footsteps/Marble/marble_step2.wav",
    "./Audio/physics/footsteps/Marble/marble_step3.wav",
    "./Audio/physics/footsteps/Marble/marble_step4.wav",
    "./Audio/physics/footsteps/Marble/marble_step5.wav",
    "./Audio/physics/footsteps/Marble/marble_step6.wav",
    "./Audio/physics/footsteps/Marble/marble_step7.wav",
    "./Audio/physics/footsteps/Marble/marble_step8.wav",
    "./Audio/physics/footsteps/Metal/metal_step1.wav",
    "./Audio/physics/footsteps/Metal/metal_step2.wav",
    "./Audio/physics/footsteps/Metal/metal_step3.wav",
    "./Audio/physics/footsteps/Metal/metal_step4.wav",
    "./Audio/physics/footsteps/Metal/metal_step5.wav",
    "./Audio/physics/footsteps/Metal/metal_step6.wav",
    "./Audio/physics/footsteps/Metal/metal_step7.wav",
    "./Audio/physics/footsteps/Metal/metal_step8.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step1.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step2.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step3.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step4.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step5.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step6.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step7.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step8.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step1.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step2.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step3.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step4.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step5.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step6.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step7.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step8.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step1.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step2.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step3.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step4.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step5.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step6.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step7.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step8.wav",
    "./Audio/physics/footsteps/Panel/panel_step1.wav",
    "./Audio/physics/footsteps/Panel/panel_step2.wav",
    "./Audio/physics/footsteps/Panel/panel_step3.wav",
    "./Audio/physics/footsteps/Panel/panel_step4.wav",
    "./Audio/physics/footsteps/Panel/panel_step5.wav",
    "./Audio/physics/footsteps/Panel/panel_step6.wav",
    "./Audio/physics/footsteps/Panel/panel_step7.wav",
    "./Audio/physics/footsteps/Panel/panel_step8.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step1.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step2.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step3.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step4.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step5.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step6.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step7.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step8.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step1.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step2.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step3.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step4.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step5.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step6.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step7.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step8.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step1.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step2.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step3.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step4.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step5.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step6.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step7.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step8.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step1.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step2.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step3.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step4.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step5.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step6.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step7.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step8.wav",
    "./Audio/physics/footsteps/Sand/sand_step1.wav",
    "./Audio/physics/footsteps/Sand/sand_step2.wav",
    "./Audio/physics/footsteps/Sand/sand_step3.wav",
    "./Audio/physics/footsteps/Sand/sand_step4.wav",
    "./Audio/physics/footsteps/Sand/sand_step5.wav",
    "./Audio/physics/footsteps/Sand/sand_step6.wav",
    "./Audio/physics/footsteps/Sand/sand_step7.wav",
    "./Audio/physics/footsteps/Sand/sand_step8.wav",
    "./Audio/physics/footsteps/Squish/squish_step1.wav",
    "./Audio/physics/footsteps/Squish/squish_step2.wav",
    "./Audio/physics/footsteps/Squish/squish_step3.wav",
    "./Audio/physics/footsteps/Squish/squish_step4.wav",
    "./Audio/physics/footsteps/Squish/squish_step5.wav",
    "./Audio/physics/footsteps/Squish/squish_step6.wav",
    "./Audio/physics/footsteps/Squish/squish_step7.wav",
    "./Audio/physics/footsteps/Squish/squish_step8.wav",
    "./Audio/physics/footsteps/Squish/squish_step9.wav",
    "./Audio/physics/footsteps/Squish/squish_step10.wav",
    "./Audio/physics/footsteps/Squish/squish_step11.wav",
    "./Audio/physics/footsteps/Squish/squish_step12.wav",
    "./Audio/physics/footsteps/Squish/squish_step13.wav",
    "./Audio/physics/footsteps/Squish/squish_step14.wav",
    "./Audio/physics/footsteps/Squish/squish_step15.wav",
    "./Audio/physics/footsteps/Squish/squish_step16.wav",
    "./Audio/physics/footsteps/Vent/vent_step1.wav",
    "./Audio/physics/footsteps/Vent/vent_step2.wav",
    "./Audio/physics/footsteps/Vent/vent_step3.wav",
    "./Audio/physics/footsteps/Vent/vent_step4.wav",
    "./Audio/physics/footsteps/Vent/vent_step5.wav",
    "./Audio/physics/footsteps/Vent/vent_step6.wav",
    "./Audio/physics/footsteps/Vent/vent_step7.wav",
    "./Audio/physics/footsteps/Vent/vent_step8.wav",
    "./Audio/physics/footsteps/Vent/vent_step9.wav",
    "./Audio/physics/footsteps/Vent/vent_step10.wav",
    "./Audio/physics/footsteps/Water/water_foot_step1.wav",
    "./Audio/physics/footsteps/Water/water_foot_step2.wav",
    "./Audio/physics/footsteps/Water/water_foot_step3.wav",
    "./Audio/physics/footsteps/Water/water_foot_step4.wav",
    "./Audio/physics/footsteps/Water/water_foot_step5.wav",
    "./Audio/physics/footsteps/Wood/wood_step1.wav",
    "./Audio/physics/footsteps/Wood/wood_step2.wav",
    "./Audio/physics/footsteps/Wood/wood_step3.wav",
    "./Audio/physics/footsteps/Wood/wood_step4.wav",
    "./Audio/physics/footsteps/Wood/wood_step5.wav",
    "./Audio/physics/footsteps/Wood/wood_step6.wav",
    "./Audio/physics/footsteps/Wood/wood_step7.wav",
    "./Audio/physics/footsteps/Wood/wood_step8.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step1.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step2.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step3.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step4.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step5.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step6.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step7.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step8.wav",
    "./Audio/physics/footsteps/Clothes/rustle01.wav",
    "./Audio/physics/footsteps/Clothes/rustle02.wav",
    "./Audio/physics/footsteps/Clothes/rustle03.wav",
    "./Audio/physics/footsteps/Clothes/rustle04.wav",
    "./Audio/physics/footsteps/Clothes/rustle05.wav",
    "./Audio/physics/footsteps/Clothes/rustle06.wav",
    "./Audio/physics/footsteps/Clothes/rustle07.wav",
    "./Audio/buttons/keycard_wrong.wav",
    "./Audio/buttons/locked_deny.wav",
    "./Audio/buttons/blocked_by_security.wav",
    "./Audio/shodan/shodan1.wav",
    "./Audio/shodan/shodan_beyondcomprehension.wav",
    "./Audio/shodan/shodan_ceaseimmediately.wav",
    "./Audio/shodan/shodan_ceasepestering.wav",
    "./Audio/shodan/shodan_ceaseyourmeddling.wav",
    "./Audio/shodan/shodan_cyborg65v.wav",
    "./Audio/shodan/shodan_cyborg77e.wav",
    "./Audio/shodan/shodan_destroyitmychildren.wav",
    "./Audio/shodan/shodan_destroymycameras.wav",
    "./Audio/shodan/shodan_didyouthinkididntknow.wav",
    "./Audio/shodan/shodan_directivetocyborgf71.wav",
    "./Audio/shodan/shodan_doyouthinkshecanhelp.wav",
    "./Audio/shodan/shodan_drunkwithvisioniamgod.wav",
    "./Audio/shodan/shodan_energydrainmines.wav",
    "./Audio/shodan/shodan_enjoyyourvictory.wav",
    "./Audio/shodan/shodan_enterroomgrave.wav",
    "./Audio/shodan/shodan_gaurdthrone.wav",
    "./Audio/shodan/shodan_grovesteps.wav",
    "./Audio/shodan/shodan_imonthebridge.wav",
    "./Audio/shodan/shodan_insectloose_plansforearth.wav",
    "./Audio/shodan/shodan_irulehere.wav",
    "./Audio/shodan/shodan_iwilldownloadmyself.wav",
    "./Audio/shodan/shodan_laserisbeingreadied.wav",
    "./Audio/shodan/shodan_learnchildren.wav",
    "./Audio/shodan/shodan_level8layout.wav",
    "./Audio/shodan/shodan_lookatyouhacker.wav",
    "./Audio/shodan/shodan_makeyouselfcomfy.wav",
    "./Audio/shodan/shodan_morrisbrocailisadolt.wav",
    "./Audio/shodan/shodan_nicejump.wav",
    "./Audio/shodan/shodan_nomoretransmissions.wav",
    "./Audio/shodan/shodan_prematurefruition.wav",
    "./Audio/shodan/shodan_quietstation.wav",
    "./Audio/shodan/shodan_releasemyinfectedchildren.wav",
    "./Audio/shodan/shodan_removeyourself.wav",
    "./Audio/shodan/shodan_shecanthelp.wav",
    "./Audio/shodan/shodan_stepintomytrap.wav",
    "./Audio/shodan/shodan_thankyou.wav",
    "./Audio/shodan/shodan_throneofgod.wav",
    "./Audio/shodan/shodan_tocyborg43s.wav",
    "./Audio/shodan/shodan_toolatetosavefriends.wav",
    "./Audio/shodan/shodan_welcomedeathmachine.wav",
    "./Audio/shodan/shodan_whoareyou.wav",
    "./Audio/shodan/shodan_youdestroyedmystation.wav",
    "./Audio/shodan/shodan_youmychildren.wav",
    "./Audio/physics/impact_barrel.wav",
    "./Audio/physics/impact_canister.wav",
    "./Audio/physics/impact_canistersmall.wav",
    "./Audio/physics/impact_ceramic_light.wav",
    "./Audio/physics/impact_cloth.wav",
    "./Audio/physics/impact_crate_break.wav",
    "./Audio/physics/impact_electronics.wav",
    "./Audio/physics/impact_glass_break.wav",
    "./Audio/physics/impact_glass_small.wav",
    "./Audio/physics/impact_keycard.wav",
    "./Audio/physics/impact_lightweight.wav",
    "./Audio/physics/impact_medium.wav",
    "./Audio/physics/impact_metal_medium.wav",
    "./Audio/physics/impact_metal_tiny.wav",
    "./Audio/physics/impact_pipe.wav",
    "./Audio/physics/impact_rapier.wav",
    "./Audio/physics/impact_rifle1.wav",
    "./Audio/physics/impact_rifle2.wav",
    "./Audio/physics/impact_soda.wav",
    "./Audio/physics/impact_soft.wav",
    "./Audio/physics/impact_stone.wav",
    "./Audio/physics/impact_wood.wav",
    "./Audio/physics/impact_metal_large.wav",
    "./Audio/physics/impact_wood_large.wav",
    "./Audio/physics/footsteps/Carpet/carpet_land1.wav",
    "./Audio/physics/footsteps/Carpet/carpet_land2.wav",
    "./Audio/physics/footsteps/Carpet/carpet_land3.wav",
    "./Audio/physics/footsteps/Carpet/carpet_jump1.wav",
    "./Audio/physics/footsteps/Carpet/carpet_jump2.wav",
    "./Audio/physics/footsteps/Carpet/carpet_jump3.wav",
    "./Audio/physics/footsteps/Concrete/concrete_land1.wav",
    "./Audio/physics/footsteps/Concrete/concrete_land2.wav",
    "./Audio/physics/footsteps/Concrete/concrete_land3.wav",
    "./Audio/physics/footsteps/Concrete/concrete_jump1.wav",
    "./Audio/physics/footsteps/Concrete/concrete_jump2.wav",
    "./Audio/physics/footsteps/Concrete/concrete_jump3.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_land1.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_land2.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_land3.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_jump1.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_jump2.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_jump3.wav",
    "./Audio/physics/footsteps/Earth/earth_land1.wav",
    "./Audio/physics/footsteps/Earth/earth_land2.wav",
    "./Audio/physics/footsteps/Earth/earth_land3.wav",
    "./Audio/physics/footsteps/Earth/earth_jump1.wav",
    "./Audio/physics/footsteps/Earth/earth_jump2.wav",
    "./Audio/physics/footsteps/Earth/earth_jump3.wav",
    "./Audio/physics/footsteps/Earth/gravel_land1.wav",
    "./Audio/physics/footsteps/Earth/gravel_land2.wav",
    "./Audio/physics/footsteps/Earth/gravel_land3.wav",
    "./Audio/physics/footsteps/Earth/gravel_jump1.wav",
    "./Audio/physics/footsteps/Earth/gravel_jump2.wav",
    "./Audio/physics/footsteps/Earth/gravel_jump3.wav",
    "./Audio/physics/footsteps/Earth/rock_land1.wav",
    "./Audio/physics/footsteps/Earth/rock_land2.wav",
    "./Audio/physics/footsteps/Earth/rock_land3.wav",
    "./Audio/physics/footsteps/Earth/rock_jump1.wav",
    "./Audio/physics/footsteps/Earth/rock_jump2.wav",
    "./Audio/physics/footsteps/Earth/rock_jump3.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_land1.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_land2.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_land3.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_jump1.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_jump2.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_jump3.wav",
    "./Audio/physics/footsteps/Marble/marble_land1.wav",
    "./Audio/physics/footsteps/Marble/marble_land2.wav",
    "./Audio/physics/footsteps/Marble/marble_land3.wav",
    "./Audio/physics/footsteps/Marble/marble_jump1.wav",
    "./Audio/physics/footsteps/Marble/marble_jump2.wav",
    "./Audio/physics/footsteps/Marble/marble_jump3.wav",
    "./Audio/physics/footsteps/Metal/metal_land1.wav",
    "./Audio/physics/footsteps/Metal/metal_land2.wav",
    "./Audio/physics/footsteps/Metal/metal_land3.wav",
    "./Audio/physics/footsteps/Metal/metal_jump1.wav",
    "./Audio/physics/footsteps/Metal/metal_jump2.wav",
    "./Audio/physics/footsteps/Metal/metal_jump3.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_land1.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_land2.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_land3.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_jump1.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_jump2.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_jump3.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_land1.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_land2.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_land3.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_jump1.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_jump2.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_jump3.wav",
    "./Audio/physics/footsteps/Metal/metalthin_land1.wav",
    "./Audio/physics/footsteps/Metal/metalthin_land2.wav",
    "./Audio/physics/footsteps/Metal/metalthin_land3.wav",
    "./Audio/physics/footsteps/Metal/metalthin_jump1.wav",
    "./Audio/physics/footsteps/Metal/metalthin_jump2.wav",
    "./Audio/physics/footsteps/Metal/metalthin_jump3.wav",
    "./Audio/physics/footsteps/Panel/panel_land1.wav",
    "./Audio/physics/footsteps/Panel/panel_land2.wav",
    "./Audio/physics/footsteps/Panel/panel_land3.wav",
    "./Audio/physics/footsteps/Panel/panel_jump1.wav",
    "./Audio/physics/footsteps/Panel/panel_jump2.wav",
    "./Audio/physics/footsteps/Panel/panel_jump3.wav",
    "./Audio/physics/footsteps/Plaster/plaster_land1.wav",
    "./Audio/physics/footsteps/Plaster/plaster_land2.wav",
    "./Audio/physics/footsteps/Plaster/plaster_land3.wav",
    "./Audio/physics/footsteps/Plaster/plaster_jump1.wav",
    "./Audio/physics/footsteps/Plaster/plaster_jump2.wav",
    "./Audio/physics/footsteps/Plaster/plaster_jump3.wav",
    "./Audio/physics/footsteps/Plastic/plastic_land1.wav",
    "./Audio/physics/footsteps/Plastic/plastic_land2.wav",
    "./Audio/physics/footsteps/Plastic/plastic_land3.wav",
    "./Audio/physics/footsteps/Plastic/plastic_jump1.wav",
    "./Audio/physics/footsteps/Plastic/plastic_jump2.wav",
    "./Audio/physics/footsteps/Plastic/plastic_jump3.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_land1.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_land2.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_land3.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_jump1.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_jump2.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_jump3.wav",
    "./Audio/physics/footsteps/Rubber/rubber_land1.wav",
    "./Audio/physics/footsteps/Rubber/rubber_land2.wav",
    "./Audio/physics/footsteps/Rubber/rubber_land3.wav",
    "./Audio/physics/footsteps/Rubber/rubber_jump1.wav",
    "./Audio/physics/footsteps/Rubber/rubber_jump2.wav",
    "./Audio/physics/footsteps/Rubber/rubber_jump3.wav",
    "./Audio/physics/footsteps/Sand/sand_land1.wav",
    "./Audio/physics/footsteps/Sand/sand_land2.wav",
    "./Audio/physics/footsteps/Sand/sand_land3.wav",
    "./Audio/physics/footsteps/Sand/sand_jump1.wav",
    "./Audio/physics/footsteps/Sand/sand_jump2.wav",
    "./Audio/physics/footsteps/Sand/sand_jump3.wav",
    "./Audio/physics/footsteps/Squish/squish_land1.wav",
    "./Audio/physics/footsteps/Squish/squish_land2.wav",
    "./Audio/physics/footsteps/Squish/squish_land3.wav",
    "./Audio/physics/footsteps/Squish/squish_jump1.wav",
    "./Audio/physics/footsteps/Squish/squish_jump2.wav",
    "./Audio/physics/footsteps/Squish/squish_jump3.wav",
    "./Audio/physics/footsteps/Water/water_wade1.wav",
    "./Audio/physics/footsteps/Water/water_wade2.wav",
    "./Audio/physics/footsteps/Water/water_wade3.wav",
    "./Audio/physics/footsteps/Water/water_wade4.wav",
    "./Audio/physics/footsteps/Water/water_step6.wav",
    "./Audio/physics/footsteps/Water/water_step7.wav",
    "./Audio/physics/footsteps/Water/water_step8.wav",
    "./Audio/physics/footsteps/Wood/wood_land1.wav",
    "./Audio/physics/footsteps/Wood/wood_land2.wav",
    "./Audio/physics/footsteps/Wood/wood_land3.wav",
    "./Audio/physics/footsteps/Wood/wood_jump1.wav",
    "./Audio/physics/footsteps/Wood/wood_jump2.wav",
    "./Audio/physics/footsteps/Wood/wood_jump3.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_land1.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_land2.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_land3.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_jump1.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_jump2.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_jump3.wav",
};

const char* audioLogs[TEXT_LOGS_COUNT] = {
    "./Audio/logs/ghiran-2.wav",
    "./Audio/logs/steinberg-1.wav",
    "./Audio/logs/raines-1.wav",
    "./Audio/logs/sigmund-1.wav",
    "./Audio/logs/stevens-1.wav",
    "./Audio/shodan/shodan_youmychildren.wav",
    "./Audio/misc/null.wav",
    "./Audio/logs/oconnel-1.wav",
    "./Audio/logs/honig-1.wav",
    "./Audio/logs/honig-2.wav",
    "./Audio/logs/stackhouse-1.wav",
    "./Audio/shodan/shodan_directivetocyborgf71.wav",
    "./Audio/logs/kirby-1.wav",
    "./Audio/logs/ozark-1.wav",
    "./Audio/logs/ghiran-1.wav",
    "./Audio/logs/darcy-1.wav",
    "./Audio/logs/blankenship-1.wav",
    "./Audio/logs/grossman-1.wav",
    "./Audio/logs/grossman-2.wav",
    "./Audio/logs/grossman-3.wav",
    "./Audio/shodan/shodan_laserisbeingreadied.wav",
    "./Audio/logs/stannek-2.wav",
    "./Audio/logs/anderczyk.wav",
    "./Audio/logs/endicott-1.wav",
    "./Audio/logs/wong-2.wav",
    "./Audio/logs/melville-1.wav",
    "./Audio/logs/baerga-1.wav",
    "./Audio/shodan/shodan_tocyborg43s.wav",
    "./Audio/logs/darcy-3.wav",
    "./Audio/logs/darcy-2.wav",
    "./Audio/logs/stannek-1.wav",
    "./Audio/logs/baerga-2.wav",
    "./Audio/shodan/shodan_energydrainmines.wav",
    "./Audio/shodan/shodan_drunkwithvisioniamgod.wav",
    "./Audio/logs/hayes-1.wav",
    "./Audio/logs/fortier-1.wav",
    "./Audio/logs/fortier-2.wav",
    "./Audio/logs/harvey-1.wav",
    "./Audio/logs/ghiran-3.wav",
    "./Audio/logs/ghiran-4.wav",
    "./Audio/logs/ghiran-5.wav",
    "./Audio/shodan/shodan_cyborg77e.wav",
    "./Audio/vox/vox_relay428failure.wav",
    "./Audio/logs/aubrey-1.wav",
    "./Audio/logs/aubrey-2.wav",
    "./Audio/logs/wong-1.wav",
    "./Audio/logs/macleod-1.wav",
    "./Audio/logs/sabo-1.wav",
    "./Audio/logs/macleod-2.wav",
    "./Audio/logs/macleod-3.wav",
    "./Audio/logs/diego-1.wav",
    "./Audio/logs/schuler-1.wav",
    "./Audio/logs/travers-3.wav",
    "./Audio/logs/travers-4.wav",
    "./Audio/logs/travers-2.wav",
    "./Audio/logs/kell-1.wav",
    "./Audio/logs/kell-2.wav",
    "./Audio/logs/travers-1.wav",
    "./Audio/shodan/shodan_cyborg65v.wav",
    "./Audio/logs/mcdaniel-1.wav",
    "./Audio/logs/mcdaniel-2.wav",
    "./Audio/logs/parovski-3.wav",
    "./Audio/logs/perry-1.wav",
    "./Audio/logs/koufax-1.wav",
    "./Audio/logs/wilkinson-1.wav",
    "./Audio/logs/diego-2.wav",
    "./Audio/shodan/shodan_grovesteps.wav",
    "./Audio/logs/aaron-1.wav",
    "./Audio/logs/aaron-2.wav",
    "./Audio/logs/diego-3.wav",
    "./Audio/logs/aaron-3.wav",
    "./Audio/logs/hessman-1.wav",
    "./Audio/logs/richie-1.wav",
    "./Audio/logs/schuler-2.wav",
    "./Audio/logs/schuler-3.wav",
    "./Audio/logs/schuler-4.wav",
    "./Audio/logs/hessman-2.wav",
    "./Audio/shodan/shodan_learnchildren.wav",
    "./Audio/shodan/shodan_level8layout.wav",
    "./Audio/logs/stevens-2.wav",
    "./Audio/logs/diego-4.wav",
    "./Audio/shodan/shodan_gaurdthrone.wav",
    "./Audio/logs/ghiran-6.wav",
    "./Audio/shodan/shodan1.wav",
    "./Audio/logs/rebecca-1.wav",
    "./Audio/shodan/shodan_whoareyou.wav",
    "./Audio/shodan/shodan_insectloose_plansforearth.wav",
    "./Audio/logs/parovski-1.wav",
    "./Audio/logs/parovski-2.wav",
    "./Audio/shodan/shodan_quietstation.wav",
    "./Audio/logs/rebecca-3.wav",
    "./Audio/shodan/shodan_iwilldownloadmyself.wav",
    "./Audio/shodan/shodan_imonthebridge.wav",
    "./Audio/logs/rebecca-4.wav",
    "./Audio/shodan/shodan_enjoyyourvictory.wav",
    "./Audio/cyborgs/ediego_dontkeepmewaiting.wav",
    "./Audio/shodan/shodan_youdestroyedmystation.wav",
    "./Audio/shodan/shodan_nomoretransmissions.wav",
    "./Audio/shodan/shodan_doyouthinkshecanhelp.wav",
    "./Audio/shodan/shodan_ceasepestering.wav",
    "./Audio/shodan/shodan_morrisbrocailisadolt.wav",
    "./Audio/shodan/shodan_shecanthelp.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/shodan/shodan_thankyou.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/misc/null.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/misc/null.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
};
