const char* creditPages[]={
"\n"
"\n"
"Click to continue...\n",


"", // Uses score screen instead for this page


"----------------------------------------------------------------------\n"
"Remake Credits\n"
"----------------------------------------------------------------------\n"
"Direct involvement list found...\n"
"\n"
"Lead Developer, Programmer, Artist, 3D Modeler\n"
"W. Josiah Jack, aka Qmaster\n"
"\n"
"-3D Modelers-\n"
"GOLD LEVEL CONTRIBUTOR: BastardRodent for most of the NPCs\n"
"RocketMan for NPC and weapon models\n"
"Chris S Evinrude for base item models\n"
"MaxEvil for base weapon models\n"
"Anders Jull Nannestad, aka Number47 for pistol ammo model\n"
"\n"
"-Artists-\n"
"Kaucukovnik for HUD icons\n"
"Gigaquad for higher res object textures\n",


"-Sound and Music-\n"
"Denhonator for remixed menu music\n"
"Nameless Voice for fluid midis\n"
"bobf5 for finding and editing original audio sources\n"

"-Misc Code-\n"
"lerenwe, Benjamin Stanley(HeadClot), cxong, Eric Haines(Eric5h5)\n",


"-Playtesters-\n"
"sverXRazum, Xkilljoy98, Berethraben,\n"
"Rachel Jack, Kaitlyn Jack, Rebecca Jack\n"
"William Van De Kieft, Trae Van Maanen\n"
"RocketMan, Denhonator, Kolya, Dertseha\n"
"JML, TheMotherload, Tjomo, Pacmikey,\n"
"Learonys, sgupta, Merudiana, SHODAN\n",


"----------------------------------------------------------------------\n"
"Indirect involvment list found...\n"
"Steven Kick and Night Dive Studios for letting this project continue!\n"
"And for providing the MAC source code of the original!\n"
"\n"
"The community on systemshock.org\n"
"\n"
"edx for a copy of System Shock Enhanced 2.5\n"
"Riky Zedd, aka Thurlik for HD Hudmaps source and reference\n"
"Speedy#3182 for his music data and pointing to ssplayer10\n"
"Ruben Torres Bonet, aka Gamedev Guru, for his technical support.\n"
"\n"
"The TTSHP Team for their many Contributions:\n"
"Jim Cameron, aka hairyjim, for engine reverse engineering\n"
"Christian Haas, aka firefreak, for HUD textures and InkyBlackness\n"
"Bryan Nolen, aka bryann, for music & sound system\n"
"Damian Gryski, for SDL support\n"
"Matt Hargett, for QA and leak detection\n"
"Glen Sawyer, for hacking source files\n"
"Jorg Fischer, for texture compression\n"
"Alistair Brown, for hacking Underworld object format\n"
"Ulf Wohlers, for hacking Underworld objects and models\n",


"----------------------------------------------------------------------\n"
"Original Game Developers (1994)\n"
"----------------------------------------------------------------------\n"
"Looking Glass Technologies\n"
"\"Salt the fries\"\n"
"\n"
"Producer\n"
"Warren Spector\n"
"\n"
"Project Leader\n"
"Doug Church\n"
"\n"
"Artists\n"
"James Alexander Dollar\n"
"Mark Lizotte\n"
"Mike Marsicano\n"
"Robb Waters\n"
"Kurt Bickenbach\n"
"\n"
"Designers\n"
"Austin Grossman\n"
"Dorian Hart\n"
"Erik Ray\n"
"Tim Stellmach\n"
"Kurt Bickenbach\n",


"Libraries\n"
"Rex E. Bradford\n"
"Laura Feeney\n"
"James Wiley Fleming\n"
"Jon Maiara\n"
"Carl Muckenhoupt\n"
"Dan Schmidt\n"
"Matt Toschlog\n"
"Kevin Wasserman\n"
"Eric Twietmeyer\n"
"\n"
"Music\n"
"Greg LoPiccolo\n"
"\n"
"Elevator Theme by\n"
"Tim Ries\n"
"\n"
"Audio Processing\n"
"Eric Brosius\n"
"Greg LoPiccolo\n"
"Tom Streit\n",


"Voiceovers\n"
"SHODAN: Terri Brosius\n"
"REBECCA LANSING: Helen Dunsmoir\n"
"EDWARD DIEGO: Austin Grossman\n"
"REX MELLVILLE: Marc LeBlanc\n"
"OTHERS: Random LG members\n"
"\n"
"Looking Glass Playtesters\n"
"Sara Verrilli\n"
"Bart Mallio\n"
"Jill Bidgood\n"
"Nick Carter\n"
"Anna Herbert\n"
"\n"
"Origin Systems Lead Playtesters\n"
"Charles Angel\n"
"Alvaro Moreno\n",


"Origin Systems Playtesters\n"
"Marshall Andrews\n"
"Bernadette Pryor\n"
"Dustin Brimberry\n"
"Brett Bonner\n"
"Harvey Smith\n"
"Jonathan Piasecki\n"
"Todd Bailey\n"
"Evan Brandt\n"
"\n"
"Programming\n"
"Doug Church\n"
"Marc LeBlanc\n"
"Vinay Pulim\n"
"Rob George Fermier\n"
"Art Min\n"
"Eli Wiesel\n"
"\n"
"Physics Programming\n"
"Seamus Blackley\n",


"Special Guest Programmer\n"
"Sean T. Barrett\n"
"\n"
"Sound System\n"
"John Miles\n"
"Fred Lim\n"
"\n"
"Translations Manager\n"
"Kirsten Vaughan\n"
"\n"
"Translations\n"
"Alpha CRC Cambridge\n"
"\n"
"French Translation\n"
"Patricia Norwood\n"
"Dominique Poumeyrol-Jumeau\n",


"French Playtesters\n"
"Didie Jumeau\n"
"\n"
"German Translation\n"
"Frank Dietz\n"
"\n"
"German Playtesters\n"
"Andreas Kohler\n"
"\n"
"Thanks to the rest of LG for putting up with us\n",


"Origin Customer Support, Marketing and Sales\n"
"\n"
"Hardware Lab\n"
"Evan Brandt\n"
"\n"
"Product Manager\n"
"Galen Svanas\n"
"Simon Etchells\n"
"\n"
"Documentation\n"
"Tuesday Frase\n"
"Harvey Smith\n"
"Alvaro Moreno\n"
"Rachel Close\n"
"and assorted ORIGIN, and Looking Glass hackers\n"
"\n"
"UK Documentation QA\n"
"Ashley Richardson\n",


"Editing\n"
"David Ladyman\n"
"Box Design\n"
"Al Carnley\n"
"Jennifer Davis\n"
"\n"
"Cover Art\n"
"Jennifer Davis\n"
"Robb Waters\n"
"\n"
"Documentation Design\n"
"Al Carnley\n"
"Jennifer Davis\n"
"Trey Hermann\n"
"Chris Morgan\n"
"Rachel Close\n"
"\n"
"Quality Assurance\n"
"Alex Camilleri (Cam-man)\n",


"----------------------------------------------------------------------\n"
"Tools\n"
"----------------------------------------------------------------------\n"
"Game Engine: Voxen, the Voxel Lit Open Source Game Engine\n"
"by W. Josiah Jack, started Apr 13 2025\n"
"\n"
"3D Modeling: Blender 2.68 through 2.79b\n"
"by the Blender Foundation headed up by Ton Roosendal\n"
"\n"
"2D Textures: GIMP 2.8 through 2.10.6\n"
"by The GIMP Development Team\n"
"\n"
"Code: Notepad++\n"
"by Don Ho and the Notepad++ Team\n"
"\n"
"Hacking: DumpTex and ss1sound\n"
"by Glen Sawyer\n"
"\n"
"Hacking: ss1edit\n"
"by ToxicFrog\n"
"\n"
"The invaluable resources at SystemShock.org\n"
"ran by Kolya\n",

"----------------------------------------------------------------------\n"
"Protoype Tools for when this project used the Unity 3D engine :( ...\n"
"\n"
"Game Engine: Unity 2020.3.48f1\n"
"by Unity Technologies\n"
"\n"
"SEGI v0.9.0 (modified by Josiah Jack)\n"
"by Cody Darr aka Sonic Ether\n"
"\n"
"NAudio\n"
"by Mark Heath\n"
"\n"
"Simple Lightning Bolt, 2016 Digital Ruby, LLC\n"
"by Jeff Johnson\n"
"\n"
"Simple File Browser\n"
"by yasirkula"
"\n"
"YamlDotNet\n"
"by Fredrik Ludvigsen\n"
"\n"
"-Misc Code-\n"
"Keijiro Takahashi, Morgan McGuire, Michael Mara, NVIDIA,\n"
"Williams College, Casual Effects, Unity Technologies, Quix0r,\n"
"WeaverDev, Nishad Tardalkar, Pacmikey\n"
"----------------------------------------------------------------------\n",


"XMI2MID and RIPXMI\n"
"by Markus Hein\n"
"\n"
"ssplayer10\n"
"by Ryan Nunn (Cless, aka Colourless)\n"
"\n"
"XWE (eXtendable Wad Editor) Version 1.16 (Thank you Trance on TTLG)\n"
"by Csabo, ReX (Gurkha Boy), Espi, Nigel Rowand (Enjay),\n"
"Russell^, Doom_Dude, Fredrik, Angst, CacodemonLeader,\n"
"Nick Baker, YicklePigeon, TZipMaster VCL by Chris\n"
"Vleghert and Eric W. Engler\n"
"\n"
"Quake BSP to VRML Converter: bsp2wrl V1.3\n"
"by Patrick McCormick\n"
"and Anthony Accardi\n"
"\n"
"Pallete Converter: palcnv12, used JASC output\n"
"by Torben Giesselmann\n"
"\n"
"Batch Converter: ImageBatch 1.2\n"
"by Dmitry Kopasov\n",


"DTValidator\n"
"by Darren Tsung\n"
"\n"
"MissingReferencesUnity\n"
"by Lior Tal aka liortal53\n"
"\n"
"MissingScriptsFinder\n"
"by Leslie Young aka plyoung\n"
"\n"
"Texture2DArray Import Pipeline\n"
"by Peter Schraut\n"
"\n"
"LightningBolt\n"
"by Jeff Johnson\n"
"\n"
"Simple File Browser\n"
"by yasirkula\n",


"----------------------------------------------------------------------\n"
"Protoype Tools for when this project\n"
"used a variant of the Quake 1 engine...\n"
"\n"
"Prototype Game Engine: DarkPlaces\n"
"by LordHavoc, aka Forest Hale and id Software\n"
"\n"
"Prototype Level Editor: Jackhammer Level Editor (JACK)\n"
"by XaeroX, DarkEssence, FreeSlave, GNU/Hurt, Phantomas, and Scrama.\n"
"\n"
"Prototype Code Editing: FTE QuakeC Compiler\n"
"by Forethough Entertainment, Spike, Moodles, Blub/0, TimeServ, Bigfoot,\n"
"Molgrum, Up2nOgOoD, RjLan, CheapAlert, purplehaze, avirox, and XavioR\n",
"\n"
"\n"
"Prototype 3D Model Exporter: Blender MDL Exporter\n"
"by Bill Currie\n"
"\n"
"Prototype 3D Model Exporter: Blender MD3 Exporter\n"
"by Derek McPherson, Xembie, PhaethonH, Bob Holcomb, Damien McGinnes,\n"
"Robert (Tr3B) Beckebans, and CoDEmanX\n"
"\n"
"Prototype Model Converter (.md3 to .mdl): md3tomdl\n"
"by Preach for converting 3d model files to Quake 1 format\n"
"\n"
"Prototype Particle Font: Particle Font\n"
"by talisa\n"
"\n"
"Prototype Colormap PCX: FULL.PCX\n"
"by Glen Sawyer\n"
"\n"
"Prototype Pallete Lump: PCX2LMP V1.1\n"
"by Richard Nichols\n"
"----------------------------------------------------------------------\n",


"======================================================================\n"
"Special Thanks\n"
"======================================================================\n"
"My wife for enduring with all my endless hours working on this project\n"
"over the years.\n"
"\n"
"\n"
"\n"
"To McDonald's for the employee reminder and vague reference:\n"
"\n"
"Don't Forget to Salt the Fries!\n",


"======================================================================\n"
"Thank you, and good night.\n"
"======================================================================\n"
"Bloodshot pizza box\n"
"Caffeine overdrive sorrow\n"
"Embrace the chaos\n"
"-Bart\n"
"\n"
"Click to continue...\n"
};
