// shadowmaps_clear.compute
// Compute shader for clearing the distances for shadowmaps in the SSBO to the light farplane of 15.36f 
#version 430 core
layout(local_size_x = 32, local_size_y = 1) in;

layout(location = 0) uniform uint lightIdx;
layout(std430,  binding = 5) buffer ShadowMaps { uint depthData[]; };

const uint FACE_SIZE = 192 * 192;

void main() {
    uint pixel = gl_GlobalInvocationID.x;
    if (pixel >= FACE_SIZE) return;
    
    depthData[(lightIdx * FACE_SIZE * 6) + (gl_WorkGroupID.y * FACE_SIZE) + pixel] = 0xFFFFFFFFu;
}
