// shadowmaps_clear.compute - Compute shader for clearing the distances for shadowmaps in the SSBO to the light farplane of 15.36f 
#version 430 core
layout(local_size_x = 32, local_size_y = 1) in;
layout(location=0) uniform uint lightIdx;
layout(location=1) uniform uint shadowMapSize;
layout(std430,binding=5) buffer ShadowMaps { uint depthData[]; };
void main() {
    uint pixel = gl_GlobalInvocationID.x;
    uint faceSize = shadowMapSize * shadowMapSize;
    if (pixel >= faceSize) return;
    
    depthData[(lightIdx * faceSize * 6) + (gl_WorkGroupID.y * faceSize) + pixel] = 0xFFFFFFFFu;
}
