// ssr.compute
// Compute shader for processing 
#version 430 core
layout(local_size_x = 32, local_size_y = 32) in;

layout(rgba8,   binding = 0) readonly uniform image2D inputImage;
layout(rgba16f, binding = 1) readonly uniform image2D inputWorldPos;
layout(rgba8,   binding = 2) readonly uniform image2D inputSpecular;

layout(rgba8,   binding = 4) uniform image2D outputImage;
layout(rg16f, binding = 5) readonly uniform image2D inputNormal;

// layout(std430, binding = 4) buffer CullingData { uint gridCellStates[]; };
// layout(std430, binding = 6) readonly buffer ModelVertexOffsets { uint vertexOffsets[]; };
// layout(std430, binding = 7) buffer BoundsBuffer { float bounds[]; };
// layout(std430, binding = 11) readonly buffer ModelVertexCounts { uint modelVertexCounts[]; };
// layout(std430, binding = 20) readonly buffer MasterVertexBuffer { float vertexData[]; };

layout(location = 0) uniform uint screenWidth;
layout(location = 1) uniform uint screenHeight;
layout(location = 2) uniform int SSR_RES;
layout(location = 3) uniform vec3 camPos;
layout(location = 4) uniform mat4 viewProjection;

vec3 DecodeOctahedral(vec2 enc) {
    enc = enc * 2.0 - 1.0;
    vec3 n = vec3(enc, 1.0 - abs(enc.x) - abs(enc.y));
    float t = max(-n.z, 0.0);
    n.xy -= t * vec2(n.x >= 0.0 ? 1.0 : -1.0, n.y >= 0.0 ? 1.0 : -1.0);
    return normalize(n);
}

// uint PosGetCellCoords(vec3 pos) {
// 	uint cellX = uint(uint(floor((pos.x - worldMin_x + CELLXHALF) / WORLDCELL_WIDTH_F)));
// 	uint cellZ = uint(uint(floor((pos.z - worldMin_z + CELLXHALF) / WORLDCELL_WIDTH_F)));
//     if (cellX > WORLDX_0BASED) cellX = WORLDX_0BASED;
//     if (cellX < 0) cellX = 0;
//     if (cellZ > WORLDX_0BASED) cellZ = WORLDX_0BASED;
//     if (cellZ < 0) cellZ = 0;
// 	return (cellZ * WORLDX) + cellX;
// }

//     if ((gridCellStates[cellIdx] & CELL_VISIBLE) == 0u && ((gridCellStates[cellIdx] & CELL_OPEN) >= 1u)) return;

// --- Ray-Triangle Intersection (Möller-Trumbore) ---
// bool RayTriangle(vec3 origin, vec3 dir, vec3 v0, vec3 v1, vec3 v2, out float t) {
//     vec3 edge1 = v1 - v0;
//     vec3 edge2 = v2 - v0;
//     vec3 h = cross(dir, edge2);
//     float a = dot(edge1, h);
//     if (abs(a) < 1e-6) return false;
// 
//     float f = 1.0 / a;
//     vec3 s = origin - v0;
//     float u = f * dot(s, h);
//     if (u < 0.0 || u > 1.0) return false;
// 
//     vec3 q = cross(s, edge1);
//     float v = f * dot(dir, q);
//     if (v < 0.0 || u + v > 1.0) return false;
// 
//     t = f * dot(edge2, q);
//     return t > 0.001;
// }
// 
// // --- Trace Ray for Shadow ---
// float TraceRay(vec3 origin, vec3 dir, float maxDist) {
//     for (int i = 0; i < instancesInPVSCount; i++) {
//         uint instanceIdx = instancesIndices[i];
//         Instance inst = instances[instanceIdx];
//         if (inst.texIndex == 881) continue; // Fullbright light
// 
//         mat4 invModel = inverse(instanceMatrices[instanceIdx]);
//         vec3 localOrigin = (invModel * vec4(origin, 1.0)).xyz;
//         float instanceRadius = bounds[instanceIdx * BOUNDS_ATTRIBUTES_COUNT + 6]; // first 6 are the mins,maxs xyz
//         if (length(localOrigin - origin) > (maxDist + instanceRadius)) continue;
// 
//         vec3 localDir = ((invModel * vec4(dir, 0.0)).xyz);
//         uint modelIndex = inst.modelIndex;
//         uint vertCount = modelVertexCounts[modelIndex];
//         if (vertCount > 1000) continue;
// 
//         uint triCount = vertCount / 3;
//         mat4 matrix = instanceMatrices[instanceIdx];
//         uint j = 0;
//         uint vertexIdx;
//         vec3 v0, v1, v2;
//         for (uint tri = 0; tri < triCount; tri++) {
//             vertexIdx = (vertexOffsets[modelIndex] * VERTEX_ATTRIBUTES_COUNT) + (tri * VERTEX_ATTRIBUTES_COUNT);
//             j = 0;
//             v0 = vec3(vertexData[vertexIdx + j * VERTEX_ATTRIBUTES_COUNT + 0], vertexData[vertexIdx + j * VERTEX_ATTRIBUTES_COUNT + 1], vertexData[vertexIdx + j * VERTEX_ATTRIBUTES_COUNT + 2]);
//             j++;
//             v1 = vec3(vertexData[vertexIdx + j * VERTEX_ATTRIBUTES_COUNT + 0], vertexData[vertexIdx + j * VERTEX_ATTRIBUTES_COUNT + 1], vertexData[vertexIdx + j * VERTEX_ATTRIBUTES_COUNT + 2]);
//             j++;
//             v2 = vec3(vertexData[vertexIdx + j * VERTEX_ATTRIBUTES_COUNT + 0], vertexData[vertexIdx + j * VERTEX_ATTRIBUTES_COUNT + 1], vertexData[vertexIdx + j * VERTEX_ATTRIBUTES_COUNT + 2]);
//             float t; // Output result
//             if (RayTriangle(localOrigin, localDir, v0, v1, v2, t) && (t < maxDist)) return 0.0;
//         }
//     }
//     return 1.0;
// }

void main() {
    uvec2 pixel = gl_GlobalInvocationID.xy;
    if (pixel.x >= screenWidth || pixel.y >= screenHeight) return;

    vec4 worldPosPack = imageLoad(inputWorldPos, ivec2(pixel * SSR_RES));
    vec3 worldPos = worldPosPack.xyz;
    vec4 specColor = imageLoad(inputSpecular, ivec2(pixel * SSR_RES));
    uint packedNormal = floatBitsToUint(imageLoad(inputNormal, ivec2(pixel * SSR_RES)).r);
    vec2 normalPack = imageLoad(inputNormal, ivec2(pixel * SSR_RES)).rg;
    vec3 normal = DecodeOctahedral(normalPack);
    vec3 viewDir = normalize(camPos - worldPos);
    vec3 reflectDir = reflect(-viewDir, normal);
    float cosTheta = max(dot(-viewDir, normal), 0.0);
    vec2 hitUV = vec2(0.0);
    vec3 reflectionColor = vec3(0.0);
    float totalWeight = 0.0;
    vec3 marchPos = worldPos + normal * 0.005;
    float traveled = 0.0;
    vec3 rayStep = reflectDir * 0.55; // stepSize
    vec2 screenSize = vec2(screenWidth, screenHeight);
    ivec2 screenSizeLess1 = ivec2(screenWidth - 1, screenHeight - 1);
    ivec2 zeroIVec2 = ivec2(0, 0);
    for (int i = 0; i < 48; ++i) { // stepCount
        marchPos += rayStep;
        traveled += 0.55; // stepSize
        vec4 clipPos = viewProjection * vec4(marchPos, 1.0);
        vec2 ndc = clipPos.xy / clipPos.w;
        hitUV = ndc * 0.5 + 0.5;
        if (hitUV.x <= 0.01 || hitUV.x >= 0.99 || hitUV.y <= 0.01 || hitUV.y >= 0.99) break;

        ivec2 samplePixel = ivec2(hitUV * screenSize);
        samplePixel = clamp(samplePixel, zeroIVec2, screenSizeLess1);
        vec4 sampledWorldPosPack = imageLoad(inputWorldPos, samplePixel * SSR_RES);
        vec3 sampledWorldPos = sampledWorldPosPack.xyz;
        vec2 sampledNormalPack = imageLoad(inputNormal, ivec2(samplePixel * SSR_RES)).rg;
        vec3 sampledNormal = DecodeOctahedral(sampledNormalPack);
        sampledNormal = normalize(sampledNormal);
        if (dot(reflectDir, sampledNormal) >= 0.0) continue;
        
        float dist2 = dot(marchPos - sampledWorldPos, marchPos - sampledWorldPos);
        float weight = exp(-dist2 / 0.05);//2.15);
        if (weight > 0.01) { // Minimum weight threshold
            ivec2 hitPixel = ivec2(hitUV * vec2(screenWidth, screenHeight));
            hitPixel = clamp(hitPixel, ivec2(0), ivec2(int(screenWidth)-1, int(screenHeight)-1));
            vec4 sampleColor = imageLoad(inputImage, hitPixel * SSR_RES);
            reflectionColor += sampleColor.rgb * weight;
            totalWeight += weight;
            if (totalWeight > 0.8) break;
        }
    }

    reflectionColor /= totalWeight; // Normalize by total weight
    vec3 result = reflectionColor * 0.251 * (specColor.rgb + vec3(0.1,0.1,0.1));
    imageStore(outputImage, ivec2(pixel), vec4(result, 1.0));
}
