// voxels.compute
// Compute shader for determining light lists for voxels and updating voxel tables 
#version 430 core
layout(local_size_x = 32, local_size_y = 32) in;

layout(std430, binding = 6) buffer VoxelLightListCounts { uint voxelLightListCounts[]; };
layout(std430, binding = 4) buffer CullingData { uint gridCellStates[]; };
layout(std430, binding = 19) buffer LightIndices { float lights[]; };
layout(std430, binding = 27) buffer UniqueLightLists { uint uniqueLightLists[]; };

layout(location = 0) uniform float voxelMinCenterX;
layout(location = 1) uniform float voxelMinCenterZ;
layout(location = 2) uniform uint loadedLights;
layout(location = 3) uniform float worldMin_x;
layout(location = 4) uniform float worldMin_z;
layout(location = 5) uniform vec3 camPos;
layout(location = 6) uniform vec3 camForward;

const int WORLD_X_VOXELCOUNT = 512;
const int MAX_LIGHTS_PER_VOXEL = 24;
const int LIGHT_DATA_SIZE = 13;
const int LIGHT_DATA_OFFSET_POSX = 0;
const int LIGHT_DATA_OFFSET_POSY = 1;
const int LIGHT_DATA_OFFSET_POSZ = 2;
const int LIGHT_DATA_OFFSET_INTENSITY = 3;
const int LIGHT_DATA_OFFSET_RANGE = 4;
const int LIGHT_DATA_OFFSET_SPOTANG = 5;
const int LIGHT_DATA_OFFSET_SPOTDIRX = 6;
const int LIGHT_DATA_OFFSET_SPOTDIRY = 7;
const int LIGHT_DATA_OFFSET_SPOTDIRZ = 8;
const int LIGHT_DATA_OFFSET_SPOTDIRW = 9;
const int LIGHT_DATA_OFFSET_R = 10;
const int LIGHT_DATA_OFFSET_G = 11;
const int LIGHT_DATA_OFFSET_B = 12;
const float VOXEL_SIZE = 0.32;
const float WORLDCELL_WIDTH_F = 2.56;
const float CELLXHALF = 1.28;
const uint WORLDX = 64;
const uint WORLDX_0BASED = 63;
const uint CELL_VISIBLE = 1u;
const uint CELL_OPEN = 2u;

uint PosGetCellCoords(vec3 pos) {
	uint cellX = uint(uint(floor((pos.x - worldMin_x + CELLXHALF) / WORLDCELL_WIDTH_F)));
	uint cellZ = uint(uint(floor((pos.z - worldMin_z + CELLXHALF) / WORLDCELL_WIDTH_F)));
    if (cellX > WORLDX_0BASED) cellX = WORLDX_0BASED;
    if (cellX < 0) cellX = 0;
    if (cellZ > WORLDX_0BASED) cellZ = WORLDX_0BASED;
    if (cellZ < 0) cellZ = 0;
	return (cellZ * WORLDX) + cellX;
}

void main() {    
    if (gl_GlobalInvocationID.x >= WORLD_X_VOXELCOUNT || gl_GlobalInvocationID.y >= WORLD_X_VOXELCOUNT) return;

    uint voxelX = gl_GlobalInvocationID.x;
    uint voxelZ = gl_GlobalInvocationID.y;
    uint voxelIndex = (voxelZ * WORLD_X_VOXELCOUNT) + voxelX;
    voxelLightListCounts[voxelIndex] = 0u;
    vec3 voxelPos = vec3(voxelMinCenterX + (voxelX * VOXEL_SIZE), 0.0, voxelMinCenterZ + (voxelZ * VOXEL_SIZE));
    vec3 cam = vec3(camPos.x, 0.0, camPos.z);
    vec3 toCam = voxelPos - cam;
    float distToVox = length(toCam);
    if (distToVox > 71.68) return;

    for (uint lightIdx = 0; lightIdx < loadedLights; ++lightIdx) {
        uint litIdx = lightIdx * LIGHT_DATA_SIZE;
        vec3 lightPos = vec3(lights[litIdx], 0.0, lights[litIdx + LIGHT_DATA_OFFSET_POSZ]);
        float range = lights[litIdx + LIGHT_DATA_OFFSET_RANGE];
        if (length(lightPos - voxelPos) < range) {
            uniqueLightLists[(voxelIndex * MAX_LIGHTS_PER_VOXEL) + voxelLightListCounts[voxelIndex]] = lightIdx;
            voxelLightListCounts[voxelIndex]++;
            if (voxelLightListCounts[voxelIndex] >= MAX_LIGHTS_PER_VOXEL) return;
        }
    }
    
    for (uint i = voxelLightListCounts[voxelIndex]; i < MAX_LIGHTS_PER_VOXEL; i++) uniqueLightLists[voxelIndex * MAX_LIGHTS_PER_VOXEL + i] = 0xFFFFFFFFu;
}
