const char* sounds[SOUNDS_COUNT] = {
    "./Audio/misc/null.wav",
    "./Audio/ambient/ambient_frogs.wav",
    "./Audio/ambient/clicker.wav",
    "./Audio/ambient/compressor.wav",
    "./Audio/ambient/dishwasher.wav",
    "./Audio/ambient/drip_amb.wav",
    "./Audio/ambient/fan1.wav",
    "./Audio/ambient/generator_gas.wav",
    "./Audio/ambient/gurgle.wav",
    "./Audio/ambient/icemaker.wav",
    "./Audio/ambient/ind_lift1.wav",
    "./Audio/ambient/ind_lift2.wav",
    "./Audio/ambient/intake.wav",
    "./Audio/ambient/lathe.wav",
    "./Audio/ambient/lava2.wav",
    "./Audio/ambient/lev3loop1.wav",
    "./Audio/ambient/lev3loop2.wav",
    "./Audio/ambient/lev3loop3.wav",
    "./Audio/ambient/lev3loop4.wav",
    "./Audio/ambient/liquid_bubble.wav",
    "./Audio/ambient/machgear_loop.wav",
    "./Audio/ambient/machine_ambience.wav",
    "./Audio/ambient/machine_go.wav",
    "./Audio/ambient/machine_humamb7.wav",
    "./Audio/ambient/machine_humlonoise.wav",
    "./Audio/ambient/machine_loop1.wav",
    "./Audio/ambient/machine_loop2.wav",
    "./Audio/ambient/machinea1.wav",
    "./Audio/ambient/machinevat_loop.wav",
    "./Audio/ambient/pipewater_loop.wav",
    "./Audio/ambient/powerloom.wav",
    "./Audio/ambient/pump.wav",
    "./Audio/ambient/pump2.wav",
    "./Audio/ambient/rain.wav",
    "./Audio/ambient/sparks1.wav",
    "./Audio/ambient/sparks2.wav",
    "./Audio/ambient/sparks3.wav",
    "./Audio/ambient/steam_loop.wav",
    "./Audio/ambient/washing_machine.wav",
    "./Audio/buttons/button_beep.wav",
    "./Audio/buttons/button_chonk.wav",
    "./Audio/buttons/button_chuck.wav",
    "./Audio/buttons/button_clickclocktuck.wav",
    "./Audio/buttons/button_deny.wav",
    "./Audio/buttons/button_lswitch.wav",
    "./Audio/buttons/button_swipe.wav",
    "./Audio/buttons/keycard_success.wav",
    "./Audio/cyborgs/cyborg_die.wav",
    "./Audio/cyborgs/cyborg_die2.wav",
    "./Audio/cyborgs/cyborg_idle2.wav",
    "./Audio/cyborgs/cyborg_shoot.wav",
    "./Audio/cyborgs/cyborgwarrior_die.wav",
    "./Audio/cyborgs/diego_blubber.wav",
    "./Audio/cyborgs/ediego_dontkeepmewaiting.wav",
    "./Audio/cyborgs/ediego_faceme.wav",
    "./Audio/cyborgs/ediego_facexecutioner.wav",
    "./Audio/cyborgs/ediego_finishexecution.wav",
    "./Audio/cyborgs/ediego_wewillmeetagain.wav",
    "./Audio/cyborgs/yourlevelsareterrible.wav",
    "./Audio/cyborgs/yourweaponsareshoddybadweapons.wav",
    "./Audio/destroy/attack1_explode.wav",
    "./Audio/destroy/camera_destroy.wav",
    "./Audio/destroy/crate_break.wav",
    "./Audio/destroy/explode_minor.wav",
    "./Audio/destroy/explosion1.wav",
    "./Audio/destroy/explosion2.wav",
    "./Audio/destroy/explosion3.wav",
    "./Audio/destroy/hit2.wav",
    "./Audio/destroy/hit3.wav",
    "./Audio/destroy/screen_destroy.wav",
    "./Audio/doors/door_platform.wav",
    "./Audio/doors/doorbulkhead_open.wav",
    "./Audio/doors/doorbulkhead_open2.wav",
    "./Audio/doors/doorcompartment_open.wav",
    "./Audio/doors/doormech_open.wav",
    "./Audio/doors/doorpnuematic_open.wav",
    "./Audio/doors/doorwall_move.wav",
    "./Audio/doors/doorwall_stop.wav",
    "./Audio/hud/activate.wav",
    "./Audio/hud/batteryuse.wav",
    "./Audio/hud/changeweapon.wav",
    "./Audio/hud/cyber.wav",
    "./Audio/hud/deactivate.wav",
    "./Audio/hud/emailalert.wav",
    "./Audio/hud/energy_gone.wav",
    "./Audio/hud/envirosuit_on.wav",
    "./Audio/hud/frob_hardware.wav",
    "./Audio/hud/frob_item.wav",
    "./Audio/hud/jumpjets_off.wav",
    "./Audio/hud/patchuse.wav",
    "./Audio/hud/radiation.wav",
    "./Audio/hud/searchsound.wav",
    "./Audio/hud/select.wav",
    "./Audio/hud/sensaround.wav",
    "./Audio/hud/shield_absorb.wav",
    "./Audio/hud/shield_off.wav",
    "./Audio/hud/shield_on.wav",
    "./Audio/hud/tab.wav",
    "./Audio/hud/targetacquire.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/misc/chargingstation.wav",
    "./Audio/misc/energy_hum.wav",
    "./Audio/misc/forcebridge.wav",
    "./Audio/misc/healstation.wav",
    "./Audio/misc/klaxon_station_alarm.wav",
    "./Audio/misc/machine_on.wav",
    "./Audio/misc/teleport.wav",
    "./Audio/misc/wing-o.wav",
    "./Audio/mutants/avianmut_attack.wav",
    "./Audio/mutants/avianmut_die.wav",
    "./Audio/mutants/avianmut_die2.wav",
    "./Audio/mutants/avianmut_sightsound.wav",
    "./Audio/mutants/footstep1.wav",
    "./Audio/mutants/footstep2.wav",
    "./Audio/mutants/footstep3.wav",
    "./Audio/mutants/footstep4.wav",
    "./Audio/mutants/footstep5.wav",
    "./Audio/mutants/gortiger_die.wav",
    "./Audio/mutants/gortiger_idle1.wav",
    "./Audio/mutants/gortiger_sightsound.wav",
    "./Audio/mutants/invisiblemut_die.wav",
    "./Audio/mutants/invisiblemut_idle1.wav",
    "./Audio/mutants/mutant_attack.wav",
    "./Audio/mutants/mutant_die.wav",
    "./Audio/mutants/plantmut_die2.wav",
    "./Audio/mutants/plantmut_throw.wav",
    "./Audio/mutants/plantmutstep1.wav",
    "./Audio/mutants/plantmutstep2.wav",
    "./Audio/mutants/plantmutstep3.wav",
    "./Audio/mutants/steplarge1.wav",
    "./Audio/mutants/steplarge2.wav",
    "./Audio/mutants/steplarge3.wav",
    "./Audio/mutants/steplarge4.wav",
    "./Audio/mutants/steplarge5.wav",
    "./Audio/mutants/virusmut_die.wav",
    "./Audio/player/jump.wav",
    "./Audio/player/jumpland.wav",
    "./Audio/player/ladder.wav",
    "./Audio/player/painalarm.wav",
    "./Audio/player/painalarmfast.wav",
    "./Audio/player/playerpain1.wav",
    "./Audio/robots/bot_destroy1.wav",
    "./Audio/robots/bot_destroy2.wav",
    "./Audio/robots/bot_destroy3.wav",
    "./Audio/robots/bot_destroy4.wav",
    "./Audio/robots/bot_destroybig.wav",
    "./Audio/robots/bot_pincherattack.wav",
    "./Audio/robots/bot_shoot1.wav",
    "./Audio/robots/bot_shoot2.wav",
    "./Audio/robots/bot_shoot3.wav",
    "./Audio/robots/bot_sight1.wav",
    "./Audio/robots/bot_sight2.wav",
    "./Audio/robots/bot_sight3.wav",
    "./Audio/robots/footfall.wav",
    "./Audio/robots/footstep1.wav",
    "./Audio/robots/footstep2.wav",
    "./Audio/robots/footstep3.wav",
    "./Audio/robots/footstephuge1.wav",
    "./Audio/robots/footstephuge2.wav",
    "./Audio/robots/footstephuge3.wav",
    "./Audio/robots/footstepsmall1.wav",
    "./Audio/robots/footstepsmall2.wav",
    "./Audio/robots/hopper_die.wav",
    "./Audio/robots/servo.wav",
    "./Audio/vox/vox_abortingprogram.wav",
    "./Audio/vox/vox_accesspanellocked.wav",
    "./Audio/vox/vox_accesspanelunlocked.wav",
    "./Audio/vox/vox_armoryaccessoverriden.wav",
    "./Audio/vox/vox_armoryaccessreinstituted.wav",
    "./Audio/vox/vox_baydoor3locked.wav",
    "./Audio/vox/vox_betagrovejettisoned.wav",
    "./Audio/vox/vox_betagrovelvatrunlocked.wav",
    "./Audio/vox/vox_biocontaminantdetected.wav",
    "./Audio/vox/vox_blastdoorlocked.wav",
    "./Audio/vox/vox_blastdoorunlocked.wav",
    "./Audio/vox/vox_bridgesepdone.wav",
    "./Audio/vox/vox_bridgesepsoon.wav",
    "./Audio/vox/vox_bridgesepstage1.wav",
    "./Audio/vox/vox_bridgesepstage2.wav",
    "./Audio/vox/vox_cameractivsecdoor.wav",
    "./Audio/vox/vox_chargeraccessgranted.wav",
    "./Audio/vox/vox_chargeroff.wav",
    "./Audio/vox/vox_corelocksdisengaged.wav",
    "./Audio/vox/vox_cybconvcancelled.wav",
    "./Audio/vox/vox_cybconvenabled.wav",
    "./Audio/vox/vox_demodsuccess.wav",
    "./Audio/vox/vox_destructcancelled.wav",
    "./Audio/vox/vox_destructnotenabled.wav",
    "./Audio/vox/vox_destructsecaccess.wav",
    "./Audio/vox/vox_doorclosedisabled.wav",
    "./Audio/vox/vox_ediegostorageclosetunlocked.wav",
    "./Audio/vox/vox_elevatordisabled.wav",
    "./Audio/vox/vox_emeraccesslocked.wav",
    "./Audio/vox/vox_entercode.wav",
    "./Audio/vox/vox_fallingairpressure.wav",
    "./Audio/vox/vox_flightbayarmoryunlocked.wav",
    "./Audio/vox/vox_forcedoor1opened.wav",
    "./Audio/vox/vox_forcedoor2opened.wav",
    "./Audio/vox/vox_forcedoor3opened.wav",
    "./Audio/vox/vox_gammajettisoned.wav",
    "./Audio/vox/vox_grovejettisoned.wav",
    "./Audio/vox/vox_grovejettisonstage1.wav",
    "./Audio/vox/vox_groveunlocked.wav",
    "./Audio/vox/vox_hallaccess.wav",
    "./Audio/vox/vox_hospitalsecdoorsopened.wav",
    "./Audio/vox/vox_jettisonalreadyenabled.wav",
    "./Audio/vox/vox_jettisonenabled.wav",
    "./Audio/vox/vox_jettisonfailure.wav",
    "./Audio/vox/vox_lifepodcancelled.wav",
    "./Audio/vox/vox_lifepodlaunchstart.wav",
    "./Audio/vox/vox_lifepodsdisabled.wav",
    "./Audio/vox/vox_maintdoorlocked.wav",
    "./Audio/vox/vox_needisotope.wav",
    "./Audio/vox/vox_nomasterjettisonenabled.wav",
    "./Audio/vox/vox_nosecaccess.wav",
    "./Audio/vox/vox_powerdivertedtor.wav",
    "./Audio/vox/vox_programinstalled.wav",
    "./Audio/vox/vox_radiationshielddeacticated.wav",
    "./Audio/vox/vox_radiationtreatdone.wav",
    "./Audio/vox/vox_reactorcountdown.wav",
    "./Audio/vox/vox_reactoroveloadstart.wav",
    "./Audio/vox/vox_reactoroverloadaccess.wav",
    "./Audio/vox/vox_reactoroverloadbypassed.wav",
    "./Audio/vox/vox_receptacleisolinearchipset.wav",
    "./Audio/vox/vox_relay428failure.wav",
    "./Audio/vox/vox_relay428faulty.wav",
    "./Audio/vox/vox_relayfixed.wav",
    "./Audio/vox/vox_replacedemodulator.wav",
    "./Audio/vox/vox_robotprodcancelled.wav",
    "./Audio/vox/vox_robotsactivated.wav",
    "./Audio/vox/vox_safetyinterlockdisabled.wav",
    "./Audio/vox/vox_safetyinterlockengaged.wav",
    "./Audio/vox/vox_safetyinterlocksenabled.wav",
    "./Audio/vox/vox_safetyoverridesonolaser.wav",
    "./Audio/vox/vox_secompoverrideneeded.wav",
    "./Audio/vox/vox_shieldgeneratorsready.wav",
    "./Audio/vox/vox_shieldson.wav",
    "./Audio/vox/vox_thelaserisdestroyed.wav",
    "./Audio/weapons/noammo.wav",
    "./Audio/weapons/wblaster.wav",
    "./Audio/weapons/wdartgun.wav",
    "./Audio/weapons/wdrill.wav",
    "./Audio/weapons/wearthshake.wav",
    "./Audio/weapons/wflechette.wav",
    "./Audio/weapons/wgrenade_arm.wav",
    "./Audio/weapons/wion.wav",
    "./Audio/weapons/wlaserrapier_hit.wav",
    "./Audio/weapons/wlaserrapier_swing.wav",
    "./Audio/weapons/wlocknload.wav",
    "./Audio/weapons/wmagnum.wav",
    "./Audio/weapons/wmagpulse.wav",
    "./Audio/weapons/wmarksman.wav",
    "./Audio/weapons/wpipe_dmg.wav",
    "./Audio/weapons/wpipe_hit.wav",
    "./Audio/weapons/wpipe_swing.wav",
    "./Audio/weapons/wpistol.wav",
    "./Audio/weapons/wpistolsilenced.wav",
    "./Audio/weapons/wplasma.wav",
    "./Audio/weapons/wpulser.wav",
    "./Audio/weapons/wrailgun.wav",
    "./Audio/weapons/wreload.wav",
    "./Audio/weapons/wricoshet.wav",
    "./Audio/weapons/wriotgun.wav",
    "./Audio/weapons/wskorpion.wav",
    "./Audio/weapons/wsparq.wav",
    "./Audio/weapons/wstungun.wav",
    "./Audio/weapons/wwoosh.wav",
    "./Audio/ambient/airhiss.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step1.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step2.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step3.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step4.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step5.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step6.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step7.wav",
    "./Audio/physics/footsteps/Carpet/carpet_step8.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step1.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step2.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step3.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step4.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step5.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step6.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step7.wav",
    "./Audio/physics/footsteps/Concrete/concrete_step8.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step1.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step2.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step3.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step4.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step5.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step6.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step7.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_step8.wav",
    "./Audio/physics/footsteps/Earth/earth_step1.wav",
    "./Audio/physics/footsteps/Earth/earth_step2.wav",
    "./Audio/physics/footsteps/Earth/earth_step3.wav",
    "./Audio/physics/footsteps/Earth/earth_step4.wav",
    "./Audio/physics/footsteps/Earth/earth_step5.wav",
    "./Audio/physics/footsteps/Earth/earth_step6.wav",
    "./Audio/physics/footsteps/Earth/earth_step7.wav",
    "./Audio/physics/footsteps/Earth/earth_step8.wav",
    "./Audio/physics/footsteps/Earth/gravel_step1.wav",
    "./Audio/physics/footsteps/Earth/gravel_step2.wav",
    "./Audio/physics/footsteps/Earth/gravel_step3.wav",
    "./Audio/physics/footsteps/Earth/gravel_step4.wav",
    "./Audio/physics/footsteps/Earth/gravel_step5.wav",
    "./Audio/physics/footsteps/Earth/gravel_step6.wav",
    "./Audio/physics/footsteps/Earth/gravel_step7.wav",
    "./Audio/physics/footsteps/Earth/gravel_step8.wav",
    "./Audio/physics/footsteps/Earth/rock_step1.wav",
    "./Audio/physics/footsteps/Earth/rock_step2.wav",
    "./Audio/physics/footsteps/Earth/rock_step3.wav",
    "./Audio/physics/footsteps/Earth/rock_step4.wav",
    "./Audio/physics/footsteps/Earth/rock_step5.wav",
    "./Audio/physics/footsteps/Earth/rock_step6.wav",
    "./Audio/physics/footsteps/Earth/rock_step7.wav",
    "./Audio/physics/footsteps/Earth/rock_step8.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step1.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step2.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step3.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step4.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step5.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step6.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step7.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_step8.wav",
    "./Audio/physics/footsteps/Marble/marble_step1.wav",
    "./Audio/physics/footsteps/Marble/marble_step2.wav",
    "./Audio/physics/footsteps/Marble/marble_step3.wav",
    "./Audio/physics/footsteps/Marble/marble_step4.wav",
    "./Audio/physics/footsteps/Marble/marble_step5.wav",
    "./Audio/physics/footsteps/Marble/marble_step6.wav",
    "./Audio/physics/footsteps/Marble/marble_step7.wav",
    "./Audio/physics/footsteps/Marble/marble_step8.wav",
    "./Audio/physics/footsteps/Metal/metal_step1.wav",
    "./Audio/physics/footsteps/Metal/metal_step2.wav",
    "./Audio/physics/footsteps/Metal/metal_step3.wav",
    "./Audio/physics/footsteps/Metal/metal_step4.wav",
    "./Audio/physics/footsteps/Metal/metal_step5.wav",
    "./Audio/physics/footsteps/Metal/metal_step6.wav",
    "./Audio/physics/footsteps/Metal/metal_step7.wav",
    "./Audio/physics/footsteps/Metal/metal_step8.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step1.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step2.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step3.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step4.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step5.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step6.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step7.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_step8.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step1.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step2.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step3.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step4.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step5.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step6.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step7.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_step8.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step1.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step2.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step3.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step4.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step5.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step6.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step7.wav",
    "./Audio/physics/footsteps/Metal/metalthin_step8.wav",
    "./Audio/physics/footsteps/Panel/panel_step1.wav",
    "./Audio/physics/footsteps/Panel/panel_step2.wav",
    "./Audio/physics/footsteps/Panel/panel_step3.wav",
    "./Audio/physics/footsteps/Panel/panel_step4.wav",
    "./Audio/physics/footsteps/Panel/panel_step5.wav",
    "./Audio/physics/footsteps/Panel/panel_step6.wav",
    "./Audio/physics/footsteps/Panel/panel_step7.wav",
    "./Audio/physics/footsteps/Panel/panel_step8.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step1.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step2.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step3.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step4.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step5.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step6.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step7.wav",
    "./Audio/physics/footsteps/Plaster/plaster_step8.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step1.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step2.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step3.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step4.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step5.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step6.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step7.wav",
    "./Audio/physics/footsteps/Plastic/plastic_step8.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step1.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step2.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step3.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step4.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step5.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step6.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step7.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_step8.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step1.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step2.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step3.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step4.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step5.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step6.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step7.wav",
    "./Audio/physics/footsteps/Rubber/rubber_step8.wav",
    "./Audio/physics/footsteps/Sand/sand_step1.wav",
    "./Audio/physics/footsteps/Sand/sand_step2.wav",
    "./Audio/physics/footsteps/Sand/sand_step3.wav",
    "./Audio/physics/footsteps/Sand/sand_step4.wav",
    "./Audio/physics/footsteps/Sand/sand_step5.wav",
    "./Audio/physics/footsteps/Sand/sand_step6.wav",
    "./Audio/physics/footsteps/Sand/sand_step7.wav",
    "./Audio/physics/footsteps/Sand/sand_step8.wav",
    "./Audio/physics/footsteps/Squish/squish_step1.wav",
    "./Audio/physics/footsteps/Squish/squish_step2.wav",
    "./Audio/physics/footsteps/Squish/squish_step3.wav",
    "./Audio/physics/footsteps/Squish/squish_step4.wav",
    "./Audio/physics/footsteps/Squish/squish_step5.wav",
    "./Audio/physics/footsteps/Squish/squish_step6.wav",
    "./Audio/physics/footsteps/Squish/squish_step7.wav",
    "./Audio/physics/footsteps/Squish/squish_step8.wav",
    "./Audio/physics/footsteps/Squish/squish_step9.wav",
    "./Audio/physics/footsteps/Squish/squish_step10.wav",
    "./Audio/physics/footsteps/Squish/squish_step11.wav",
    "./Audio/physics/footsteps/Squish/squish_step12.wav",
    "./Audio/physics/footsteps/Squish/squish_step13.wav",
    "./Audio/physics/footsteps/Squish/squish_step14.wav",
    "./Audio/physics/footsteps/Squish/squish_step15.wav",
    "./Audio/physics/footsteps/Squish/squish_step16.wav",
    "./Audio/physics/footsteps/Vent/vent_step1.wav",
    "./Audio/physics/footsteps/Vent/vent_step2.wav",
    "./Audio/physics/footsteps/Vent/vent_step3.wav",
    "./Audio/physics/footsteps/Vent/vent_step4.wav",
    "./Audio/physics/footsteps/Vent/vent_step5.wav",
    "./Audio/physics/footsteps/Vent/vent_step6.wav",
    "./Audio/physics/footsteps/Vent/vent_step7.wav",
    "./Audio/physics/footsteps/Vent/vent_step8.wav",
    "./Audio/physics/footsteps/Vent/vent_step9.wav",
    "./Audio/physics/footsteps/Vent/vent_step10.wav",
    "./Audio/physics/footsteps/Water/water_foot_step1.wav",
    "./Audio/physics/footsteps/Water/water_foot_step2.wav",
    "./Audio/physics/footsteps/Water/water_foot_step3.wav",
    "./Audio/physics/footsteps/Water/water_foot_step4.wav",
    "./Audio/physics/footsteps/Water/water_foot_step5.wav",
    "./Audio/physics/footsteps/Wood/wood_step1.wav",
    "./Audio/physics/footsteps/Wood/wood_step2.wav",
    "./Audio/physics/footsteps/Wood/wood_step3.wav",
    "./Audio/physics/footsteps/Wood/wood_step4.wav",
    "./Audio/physics/footsteps/Wood/wood_step5.wav",
    "./Audio/physics/footsteps/Wood/wood_step6.wav",
    "./Audio/physics/footsteps/Wood/wood_step7.wav",
    "./Audio/physics/footsteps/Wood/wood_step8.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step1.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step2.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step3.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step4.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step5.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step6.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step7.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_step8.wav",
    "./Audio/physics/footsteps/Clothes/rustle01.wav",
    "./Audio/physics/footsteps/Clothes/rustle02.wav",
    "./Audio/physics/footsteps/Clothes/rustle03.wav",
    "./Audio/physics/footsteps/Clothes/rustle04.wav",
    "./Audio/physics/footsteps/Clothes/rustle05.wav",
    "./Audio/physics/footsteps/Clothes/rustle06.wav",
    "./Audio/physics/footsteps/Clothes/rustle07.wav",
    "./Audio/buttons/keycard_wrong.wav",
    "./Audio/buttons/locked_deny.wav",
    "./Audio/buttons/blocked_by_security.wav",
    "./Audio/shodan/shodan1.wav",
    "./Audio/shodan/shodan_beyondcomprehension.wav",
    "./Audio/shodan/shodan_ceaseimmediately.wav",
    "./Audio/shodan/shodan_ceasepestering.wav",
    "./Audio/shodan/shodan_ceaseyourmeddling.wav",
    "./Audio/shodan/shodan_cyborg65v.wav",
    "./Audio/shodan/shodan_cyborg77e.wav",
    "./Audio/shodan/shodan_destroyitmychildren.wav",
    "./Audio/shodan/shodan_destroymycameras.wav",
    "./Audio/shodan/shodan_didyouthinkididntknow.wav",
    "./Audio/shodan/shodan_directivetocyborgf71.wav",
    "./Audio/shodan/shodan_doyouthinkshecanhelp.wav",
    "./Audio/shodan/shodan_drunkwithvisioniamgod.wav",
    "./Audio/shodan/shodan_energydrainmines.wav",
    "./Audio/shodan/shodan_enjoyyourvictory.wav",
    "./Audio/shodan/shodan_enterroomgrave.wav",
    "./Audio/shodan/shodan_gaurdthrone.wav",
    "./Audio/shodan/shodan_grovesteps.wav",
    "./Audio/shodan/shodan_imonthebridge.wav",
    "./Audio/shodan/shodan_insectloose_plansforearth.wav",
    "./Audio/shodan/shodan_irulehere.wav",
    "./Audio/shodan/shodan_iwilldownloadmyself.wav",
    "./Audio/shodan/shodan_laserisbeingreadied.wav",
    "./Audio/shodan/shodan_learnchildren.wav",
    "./Audio/shodan/shodan_level8layout.wav",
    "./Audio/shodan/shodan_lookatyouhacker.wav",
    "./Audio/shodan/shodan_makeyouselfcomfy.wav",
    "./Audio/shodan/shodan_morrisbrocailisadolt.wav",
    "./Audio/shodan/shodan_nicejump.wav",
    "./Audio/shodan/shodan_nomoretransmissions.wav",
    "./Audio/shodan/shodan_prematurefruition.wav",
    "./Audio/shodan/shodan_quietstation.wav",
    "./Audio/shodan/shodan_releasemyinfectedchildren.wav",
    "./Audio/shodan/shodan_removeyourself.wav",
    "./Audio/shodan/shodan_shecanthelp.wav",
    "./Audio/shodan/shodan_stepintomytrap.wav",
    "./Audio/shodan/shodan_thankyou.wav",
    "./Audio/shodan/shodan_throneofgod.wav",
    "./Audio/shodan/shodan_tocyborg43s.wav",
    "./Audio/shodan/shodan_toolatetosavefriends.wav",
    "./Audio/shodan/shodan_welcomedeathmachine.wav",
    "./Audio/shodan/shodan_whoareyou.wav",
    "./Audio/shodan/shodan_youdestroyedmystation.wav",
    "./Audio/shodan/shodan_youmychildren.wav",
    "./Audio/physics/impact_barrel.wav",
    "./Audio/physics/impact_canister.wav",
    "./Audio/physics/impact_canistersmall.wav",
    "./Audio/physics/impact_ceramic_light.wav",
    "./Audio/physics/impact_cloth.wav",
    "./Audio/physics/impact_crate_break.wav",
    "./Audio/physics/impact_electronics.wav",
    "./Audio/physics/impact_glass_break.wav",
    "./Audio/physics/impact_glass_small.wav",
    "./Audio/physics/impact_keycard.wav",
    "./Audio/physics/impact_lightweight.wav",
    "./Audio/physics/impact_medium.wav",
    "./Audio/physics/impact_metal_medium.wav",
    "./Audio/physics/impact_metal_tiny.wav",
    "./Audio/physics/impact_pipe.wav",
    "./Audio/physics/impact_rapier.wav",
    "./Audio/physics/impact_rifle1.wav",
    "./Audio/physics/impact_rifle2.wav",
    "./Audio/physics/impact_soda.wav",
    "./Audio/physics/impact_soft.wav",
    "./Audio/physics/impact_stone.wav",
    "./Audio/physics/impact_wood.wav",
    "./Audio/physics/impact_metal_large.wav",
    "./Audio/physics/impact_wood_large.wav",
    "./Audio/physics/footsteps/Carpet/carpet_land1.wav",
    "./Audio/physics/footsteps/Carpet/carpet_land2.wav",
    "./Audio/physics/footsteps/Carpet/carpet_land3.wav",
    "./Audio/physics/footsteps/Carpet/carpet_jump1.wav",
    "./Audio/physics/footsteps/Carpet/carpet_jump2.wav",
    "./Audio/physics/footsteps/Carpet/carpet_jump3.wav",
    "./Audio/physics/footsteps/Concrete/concrete_land1.wav",
    "./Audio/physics/footsteps/Concrete/concrete_land2.wav",
    "./Audio/physics/footsteps/Concrete/concrete_land3.wav",
    "./Audio/physics/footsteps/Concrete/concrete_jump1.wav",
    "./Audio/physics/footsteps/Concrete/concrete_jump2.wav",
    "./Audio/physics/footsteps/Concrete/concrete_jump3.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_land1.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_land2.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_land3.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_jump1.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_jump2.wav",
    "./Audio/physics/footsteps/Concrete Gritty/concrete_grit_jump3.wav",
    "./Audio/physics/footsteps/Earth/earth_land1.wav",
    "./Audio/physics/footsteps/Earth/earth_land2.wav",
    "./Audio/physics/footsteps/Earth/earth_land3.wav",
    "./Audio/physics/footsteps/Earth/earth_jump1.wav",
    "./Audio/physics/footsteps/Earth/earth_jump2.wav",
    "./Audio/physics/footsteps/Earth/earth_jump3.wav",
    "./Audio/physics/footsteps/Earth/gravel_land1.wav",
    "./Audio/physics/footsteps/Earth/gravel_land2.wav",
    "./Audio/physics/footsteps/Earth/gravel_land3.wav",
    "./Audio/physics/footsteps/Earth/gravel_jump1.wav",
    "./Audio/physics/footsteps/Earth/gravel_jump2.wav",
    "./Audio/physics/footsteps/Earth/gravel_jump3.wav",
    "./Audio/physics/footsteps/Earth/rock_land1.wav",
    "./Audio/physics/footsteps/Earth/rock_land2.wav",
    "./Audio/physics/footsteps/Earth/rock_land3.wav",
    "./Audio/physics/footsteps/Earth/rock_jump1.wav",
    "./Audio/physics/footsteps/Earth/rock_jump2.wav",
    "./Audio/physics/footsteps/Earth/rock_jump3.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_land1.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_land2.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_land3.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_jump1.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_jump2.wav",
    "./Audio/physics/footsteps/Glass/glasssolid_jump3.wav",
    "./Audio/physics/footsteps/Marble/marble_land1.wav",
    "./Audio/physics/footsteps/Marble/marble_land2.wav",
    "./Audio/physics/footsteps/Marble/marble_land3.wav",
    "./Audio/physics/footsteps/Marble/marble_jump1.wav",
    "./Audio/physics/footsteps/Marble/marble_jump2.wav",
    "./Audio/physics/footsteps/Marble/marble_jump3.wav",
    "./Audio/physics/footsteps/Metal/metal_land1.wav",
    "./Audio/physics/footsteps/Metal/metal_land2.wav",
    "./Audio/physics/footsteps/Metal/metal_land3.wav",
    "./Audio/physics/footsteps/Metal/metal_jump1.wav",
    "./Audio/physics/footsteps/Metal/metal_jump2.wav",
    "./Audio/physics/footsteps/Metal/metal_jump3.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_land1.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_land2.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_land3.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_jump1.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_jump2.wav",
    "./Audio/physics/footsteps/Metal/metalgrate_jump3.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_land1.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_land2.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_land3.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_jump1.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_jump2.wav",
    "./Audio/physics/footsteps/Metal/metalsolid_jump3.wav",
    "./Audio/physics/footsteps/Metal/metalthin_land1.wav",
    "./Audio/physics/footsteps/Metal/metalthin_land2.wav",
    "./Audio/physics/footsteps/Metal/metalthin_land3.wav",
    "./Audio/physics/footsteps/Metal/metalthin_jump1.wav",
    "./Audio/physics/footsteps/Metal/metalthin_jump2.wav",
    "./Audio/physics/footsteps/Metal/metalthin_jump3.wav",
    "./Audio/physics/footsteps/Panel/panel_land1.wav",
    "./Audio/physics/footsteps/Panel/panel_land2.wav",
    "./Audio/physics/footsteps/Panel/panel_land3.wav",
    "./Audio/physics/footsteps/Panel/panel_jump1.wav",
    "./Audio/physics/footsteps/Panel/panel_jump2.wav",
    "./Audio/physics/footsteps/Panel/panel_jump3.wav",
    "./Audio/physics/footsteps/Plaster/plaster_land1.wav",
    "./Audio/physics/footsteps/Plaster/plaster_land2.wav",
    "./Audio/physics/footsteps/Plaster/plaster_land3.wav",
    "./Audio/physics/footsteps/Plaster/plaster_jump1.wav",
    "./Audio/physics/footsteps/Plaster/plaster_jump2.wav",
    "./Audio/physics/footsteps/Plaster/plaster_jump3.wav",
    "./Audio/physics/footsteps/Plastic/plastic_land1.wav",
    "./Audio/physics/footsteps/Plastic/plastic_land2.wav",
    "./Audio/physics/footsteps/Plastic/plastic_land3.wav",
    "./Audio/physics/footsteps/Plastic/plastic_jump1.wav",
    "./Audio/physics/footsteps/Plastic/plastic_jump2.wav",
    "./Audio/physics/footsteps/Plastic/plastic_jump3.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_land1.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_land2.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_land3.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_jump1.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_jump2.wav",
    "./Audio/physics/footsteps/Plastic/plasticsolid_jump3.wav",
    "./Audio/physics/footsteps/Rubber/rubber_land1.wav",
    "./Audio/physics/footsteps/Rubber/rubber_land2.wav",
    "./Audio/physics/footsteps/Rubber/rubber_land3.wav",
    "./Audio/physics/footsteps/Rubber/rubber_jump1.wav",
    "./Audio/physics/footsteps/Rubber/rubber_jump2.wav",
    "./Audio/physics/footsteps/Rubber/rubber_jump3.wav",
    "./Audio/physics/footsteps/Sand/sand_land1.wav",
    "./Audio/physics/footsteps/Sand/sand_land2.wav",
    "./Audio/physics/footsteps/Sand/sand_land3.wav",
    "./Audio/physics/footsteps/Sand/sand_jump1.wav",
    "./Audio/physics/footsteps/Sand/sand_jump2.wav",
    "./Audio/physics/footsteps/Sand/sand_jump3.wav",
    "./Audio/physics/footsteps/Squish/squish_land1.wav",
    "./Audio/physics/footsteps/Squish/squish_land2.wav",
    "./Audio/physics/footsteps/Squish/squish_land3.wav",
    "./Audio/physics/footsteps/Squish/squish_jump1.wav",
    "./Audio/physics/footsteps/Squish/squish_jump2.wav",
    "./Audio/physics/footsteps/Squish/squish_jump3.wav",
    "./Audio/physics/footsteps/Water/water_wade1.wav",
    "./Audio/physics/footsteps/Water/water_wade2.wav",
    "./Audio/physics/footsteps/Water/water_wade3.wav",
    "./Audio/physics/footsteps/Water/water_wade4.wav",
    "./Audio/physics/footsteps/Water/water_step6.wav",
    "./Audio/physics/footsteps/Water/water_step7.wav",
    "./Audio/physics/footsteps/Water/water_step8.wav",
    "./Audio/physics/footsteps/Wood/wood_land1.wav",
    "./Audio/physics/footsteps/Wood/wood_land2.wav",
    "./Audio/physics/footsteps/Wood/wood_land3.wav",
    "./Audio/physics/footsteps/Wood/wood_jump1.wav",
    "./Audio/physics/footsteps/Wood/wood_jump2.wav",
    "./Audio/physics/footsteps/Wood/wood_jump3.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_land1.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_land2.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_land3.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_jump1.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_jump2.wav",
    "./Audio/physics/footsteps/Wood/woodcrate_jump3.wav",
};

const char* audioLogs[T_LOGS_COUNT] = {
    "./Audio/logs/ghiran-2.wav",
    "./Audio/logs/steinberg-1.wav",
    "./Audio/logs/raines-1.wav",
    "./Audio/logs/sigmund-1.wav",
    "./Audio/logs/stevens-1.wav",
    "./Audio/shodan/shodan_youmychildren.wav",
    "./Audio/misc/null.wav",
    "./Audio/logs/oconnel-1.wav",
    "./Audio/logs/honig-1.wav",
    "./Audio/logs/honig-2.wav",
    "./Audio/logs/stackhouse-1.wav",
    "./Audio/shodan/shodan_directivetocyborgf71.wav",
    "./Audio/logs/kirby-1.wav",
    "./Audio/logs/ozark-1.wav",
    "./Audio/logs/ghiran-1.wav",
    "./Audio/logs/darcy-1.wav",
    "./Audio/logs/blankenship-1.wav",
    "./Audio/logs/grossman-1.wav",
    "./Audio/logs/grossman-2.wav",
    "./Audio/logs/grossman-3.wav",
    "./Audio/shodan/shodan_laserisbeingreadied.wav",
    "./Audio/logs/stannek-2.wav",
    "./Audio/logs/anderczyk.wav",
    "./Audio/logs/endicott-1.wav",
    "./Audio/logs/wong-2.wav",
    "./Audio/logs/melville-1.wav",
    "./Audio/logs/baerga-1.wav",
    "./Audio/shodan/shodan_tocyborg43s.wav",
    "./Audio/logs/darcy-3.wav",
    "./Audio/logs/darcy-2.wav",
    "./Audio/logs/stannek-1.wav",
    "./Audio/logs/baerga-2.wav",
    "./Audio/shodan/shodan_energydrainmines.wav",
    "./Audio/shodan/shodan_drunkwithvisioniamgod.wav",
    "./Audio/logs/hayes-1.wav",
    "./Audio/logs/fortier-1.wav",
    "./Audio/logs/fortier-2.wav",
    "./Audio/logs/harvey-1.wav",
    "./Audio/logs/ghiran-3.wav",
    "./Audio/logs/ghiran-4.wav",
    "./Audio/logs/ghiran-5.wav",
    "./Audio/shodan/shodan_cyborg77e.wav",
    "./Audio/vox/vox_relay428failure.wav",
    "./Audio/logs/aubrey-1.wav",
    "./Audio/logs/aubrey-2.wav",
    "./Audio/logs/wong-1.wav",
    "./Audio/logs/macleod-1.wav",
    "./Audio/logs/sabo-1.wav",
    "./Audio/logs/macleod-2.wav",
    "./Audio/logs/macleod-3.wav",
    "./Audio/logs/diego-1.wav",
    "./Audio/logs/schuler-1.wav",
    "./Audio/logs/travers-3.wav",
    "./Audio/logs/travers-4.wav",
    "./Audio/logs/travers-2.wav",
    "./Audio/logs/kell-1.wav",
    "./Audio/logs/kell-2.wav",
    "./Audio/logs/travers-1.wav",
    "./Audio/shodan/shodan_cyborg65v.wav",
    "./Audio/logs/mcdaniel-1.wav",
    "./Audio/logs/mcdaniel-2.wav",
    "./Audio/logs/parovski-3.wav",
    "./Audio/logs/perry-1.wav",
    "./Audio/logs/koufax-1.wav",
    "./Audio/logs/wilkinson-1.wav",
    "./Audio/logs/diego-2.wav",
    "./Audio/shodan/shodan_grovesteps.wav",
    "./Audio/logs/aaron-1.wav",
    "./Audio/logs/aaron-2.wav",
    "./Audio/logs/diego-3.wav",
    "./Audio/logs/aaron-3.wav",
    "./Audio/logs/hessman-1.wav",
    "./Audio/logs/richie-1.wav",
    "./Audio/logs/schuler-2.wav",
    "./Audio/logs/schuler-3.wav",
    "./Audio/logs/schuler-4.wav",
    "./Audio/logs/hessman-2.wav",
    "./Audio/shodan/shodan_learnchildren.wav",
    "./Audio/shodan/shodan_level8layout.wav",
    "./Audio/logs/stevens-2.wav",
    "./Audio/logs/diego-4.wav",
    "./Audio/shodan/shodan_gaurdthrone.wav",
    "./Audio/logs/ghiran-6.wav",
    "./Audio/shodan/shodan1.wav",
    "./Audio/logs/rebecca-1.wav",
    "./Audio/shodan/shodan_whoareyou.wav",
    "./Audio/shodan/shodan_insectloose_plansforearth.wav",
    "./Audio/logs/parovski-1.wav",
    "./Audio/logs/parovski-2.wav",
    "./Audio/shodan/shodan_quietstation.wav",
    "./Audio/logs/rebecca-3.wav",
    "./Audio/shodan/shodan_iwilldownloadmyself.wav",
    "./Audio/shodan/shodan_imonthebridge.wav",
    "./Audio/logs/rebecca-4.wav",
    "./Audio/shodan/shodan_enjoyyourvictory.wav",
    "./Audio/cyborgs/ediego_dontkeepmewaiting.wav",
    "./Audio/shodan/shodan_youdestroyedmystation.wav",
    "./Audio/shodan/shodan_nomoretransmissions.wav",
    "./Audio/shodan/shodan_doyouthinkshecanhelp.wav",
    "./Audio/shodan/shodan_ceasepestering.wav",
    "./Audio/shodan/shodan_morrisbrocailisadolt.wav",
    "./Audio/shodan/shodan_shecanthelp.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/shodan/shodan_thankyou.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/misc/null.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/misc/null.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/hud/vmailalert.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
    "./Audio/misc/null.wav",
};

FootStepType GetFootstepTypeForPrefab(int pid) {
    if (pid == 0 || (pid >= 21 && pid <= 22)) return FootStepType_None;
    if ((pid >= 2 && pid <= 10) || (pid >= 98 && pid <= 100) || pid == 110) return FootStepType_Squish;
    if ((pid >= 13 && pid <= 18) || (pid >= 82 && pid <= 88)) return FootStepType_Metal2;
    if ((pid >= 23 && pid <= 40) || pid == 48 || pid == 49 || pid == 53) return FootStepType_Plastic2;
    if ((pid >= 41 && pid <= 47) || (pid >= 149 && pid <= 159)) return FootStepType_Plastic;
    if (pid >= 64 && pid <= 66) return FootStepType_Sand;
    if (pid >= 94 && pid <= 96) return FootStepType_Grass;
    if ((pid >= 101 && pid <= 109) || pid == 111) return FootStepType_GrittyCrete;
    if (pid >= 144 && pid <= 148) return FootStepType_Vent;
    if (pid >= 131 && pid <= 134) return FootStepType_Metal;
    if (pid == 1 || pid == 19 || pid == 77 || pid == 93 || pid == 122 || pid == 126 || pid == 128 || pid == 187 || pid == 221 || (pid >= 235 && pid <= 237) || (pid >= 260 && pid <= 261) || (pid >= 270 && pid <= 271) || pid == 279) return FootStepType_Glass;
    if (pid == 11 || (pid >= 51 && pid <= 52) || (pid >= 56 && pid <= 57) || pid == 71 || (pid >= 116 && pid <= 117) || (pid >= 120 && pid <= 121) || (pid >= 135 && pid <= 136) || (pid >= 139 && pid <= 140) || (pid >= 204 && pid <= 207) || (pid >= 458 && pid <= 460) || (pid >= 477 && pid <= 479)) return FootStepType_Metpanel;
    if (pid == 12 || pid == 61 || (pid >= 72 && pid <= 73) || pid == 76 || (pid >= 280 && pid <= 287)) return FootStepType_Marble;
    if (pid == 20 || pid == 464 || (pid >= 472 && pid <= 476)) return FootStepType_Wood2;
    if (pid == 50 || pid == 70 || pid == 75) return FootStepType_Carpet;
    if (pid >= 54 && pid <= 55) return FootStepType_Gravel;
    if ((pid >= 62 && pid <= 63) || pid == 78 || pid == 89 || pid == 112 || pid == 127 || pid == 129 || (pid >= 137 && pid <= 138) || (pid >= 141 && pid <= 143) || pid == 189 || pid == 196 || (pid >= 208 && pid <= 220) || (pid >= 222 && pid <= 230) || (pid >= 238 && pid <= 240) || (pid >= 292 && pid <= 301) || pid == 305 || pid == 461 || pid == 463 || pid == 500 || pid == 516 || (pid >= 525 && pid <= 526)) return FootStepType_Metal;
    if (pid == 74 || pid == 306) return FootStepType_Plaster;
    if (pid == 79 || pid == 130 || pid == 231 || (pid >= 262 && pid <= 265) || (pid >= 527 && pid <= 529)) return FootStepType_Grate;
    if ((pid >= 80 && pid <= 81) || (pid >= 124 && pid <= 125) || (pid >= 302 && pid <= 304)) return FootStepType_Rubber;
    if (pid == 97) return FootStepType_Water;
    if ((pid >= 113 && pid <= 115) || (pid >= 118 && pid <= 119) || pid == 123 || (pid >= 160 && pid <= 161) || (pid >= 169 && pid <= 177) || (pid >= 253 && pid <= 255) || pid == 515) return FootStepType_Panel;
    return FootStepType_Plastic; // default
}

const char* JumpSound(FootStepType fstep) {
    switch(fstep) {
        case FootStepType_None: return sounds[0];
        // + 1 because its exclusive, :eyeroll:
        case FootStepType_Carpet:      return sounds[random_range_u32(540,542 + 1)];
        case FootStepType_Concrete:    return sounds[random_range_u32(546,548 + 1)];
        case FootStepType_GrittyCrete: return sounds[random_range_u32(552,554 + 1)];
        case FootStepType_Grass:       return sounds[random_range_u32(558,560 + 1)];
        case FootStepType_Gravel:      return sounds[random_range_u32(564,566 + 1)];
        case FootStepType_Rock:        return sounds[random_range_u32(570,572 + 1)];
        case FootStepType_Glass:       return sounds[random_range_u32(576,578 + 1)];
        case FootStepType_Marble:      return sounds[random_range_u32(582,584 + 1)];
        case FootStepType_Metal:       return sounds[random_range_u32(588,590 + 1)];
        case FootStepType_Grate:       return sounds[random_range_u32(594,596 + 1)];
        case FootStepType_Metal2:      return sounds[random_range_u32(600,602 + 1)];
        case FootStepType_Metpanel:    return sounds[random_range_u32(606,608 + 1)];
        case FootStepType_Panel:       return sounds[random_range_u32(612,614 + 1)];
        case FootStepType_Plaster:     return sounds[random_range_u32(618,620 + 1)];
        case FootStepType_Plastic:     return sounds[random_range_u32(624,626 + 1)];
        case FootStepType_Plastic2:    return sounds[random_range_u32(630,632 + 1)];
        case FootStepType_Rubber:      return sounds[random_range_u32(636,638 + 1)];
        case FootStepType_Sand:        return sounds[random_range_u32(642,644 + 1)];
        case FootStepType_Squish:      return sounds[random_range_u32(648,650 + 1)];
        case FootStepType_Vent:        return sounds[random_range_u32(429,430 + 1)];
        case FootStepType_Water:       return sounds[random_range_u32(651,654 + 1)];
        case FootStepType_Wood:        return sounds[random_range_u32(661,663 + 1)];
        case FootStepType_Wood2:       return sounds[random_range_u32(667,669 + 1)];
    }
    
    return sounds[0]; // null wav fallback
}
	
const char* JumpLandSound(FootStepType fstep) {
    switch(fstep) {
        case FootStepType_None: return sounds[0];
        // + 1 because its exclusive, :eyeroll:
        case FootStepType_Carpet:      return sounds[random_range_u32(537,539 + 1)];
        case FootStepType_Concrete:    return sounds[random_range_u32(543,545 + 1)];
        case FootStepType_GrittyCrete: return sounds[random_range_u32(549,551 + 1)];
        case FootStepType_Grass:       return sounds[random_range_u32(555,557 + 1)];
        case FootStepType_Gravel:      return sounds[random_range_u32(561,563 + 1)];
        case FootStepType_Rock:        return sounds[random_range_u32(567,569 + 1)];
        case FootStepType_Glass:       return sounds[random_range_u32(573,575 + 1)];
        case FootStepType_Marble:      return sounds[random_range_u32(579,581 + 1)];
        case FootStepType_Metal:       return sounds[random_range_u32(585,587 + 1)];
        case FootStepType_Grate:       return sounds[random_range_u32(591,593 + 1)];
        case FootStepType_Metal2:      return sounds[random_range_u32(597,599 + 1)];
        case FootStepType_Metpanel:    return sounds[random_range_u32(603,605 + 1)];
        case FootStepType_Panel:       return sounds[random_range_u32(609,611 + 1)];
        case FootStepType_Plaster:     return sounds[random_range_u32(615,617 + 1)];
        case FootStepType_Plastic:     return sounds[random_range_u32(621,623 + 1)];
        case FootStepType_Plastic2:    return sounds[random_range_u32(627,629 + 1)];
        case FootStepType_Rubber:      return sounds[random_range_u32(633,635 + 1)];
        case FootStepType_Sand:        return sounds[random_range_u32(639,641 + 1)];
        case FootStepType_Squish:      return sounds[random_range_u32(645,647 + 1)];
        case FootStepType_Vent:        return sounds[random_range_u32(428,437 + 1)];
        case FootStepType_Water:       return sounds[random_range_u32(655,657 + 1)];
        case FootStepType_Wood:        return sounds[random_range_u32(658,660 + 1)];
        case FootStepType_Wood2:       return sounds[random_range_u32(664,666 + 1)];
    }
    
    return sounds[0]; // null wav fallback
}

const char* FootStepSound(FootStepType fstep) {
    switch(fstep) {
        case FootStepType_None: return sounds[0];
        // + 1 because its exclusive, :eyeroll:
        case FootStepType_Carpet:      return sounds[random_range_u32(268,275 + 1)];
        case FootStepType_Concrete:    return sounds[random_range_u32(276,283 + 1)];
        case FootStepType_GrittyCrete: return sounds[random_range_u32(284,291 + 1)];
        case FootStepType_Grass:       return sounds[random_range_u32(292,299 + 1)];
        case FootStepType_Gravel:      return sounds[random_range_u32(300,307 + 1)];
        case FootStepType_Rock:        return sounds[random_range_u32(308,315 + 1)];
        case FootStepType_Glass:       return sounds[random_range_u32(316,323 + 1)];
        case FootStepType_Marble:      return sounds[random_range_u32(324,331 + 1)];
        case FootStepType_Metal:       return sounds[random_range_u32(332,339 + 1)];
        case FootStepType_Grate:       return sounds[random_range_u32(340,347 + 1)];
        case FootStepType_Metal2:      return sounds[random_range_u32(348,355 + 1)];
        case FootStepType_Metpanel:    return sounds[random_range_u32(356,363 + 1)];
        case FootStepType_Panel:       return sounds[random_range_u32(364,371 + 1)];
        case FootStepType_Plaster:     return sounds[random_range_u32(372,379 + 1)];
        case FootStepType_Plastic:     return sounds[random_range_u32(380,387 + 1)];
        case FootStepType_Plastic2:    return sounds[random_range_u32(388,395 + 1)];
        case FootStepType_Rubber:      return sounds[random_range_u32(396,403 + 1)];
        case FootStepType_Sand:        return sounds[random_range_u32(404,411 + 1)];
        case FootStepType_Squish:      return sounds[random_range_u32(412,427 + 1)];
        case FootStepType_Vent:        return sounds[random_range_u32(428,437 + 1)];
        case FootStepType_Water:       return sounds[random_range_u32(438,442 + 1)];
        case FootStepType_Wood:        return sounds[random_range_u32(443,450 + 1)];
        case FootStepType_Wood2:       return sounds[random_range_u32(451,458 + 1)];
    }

    return sounds[0]; // null wav
}
