#!/usr/bin/env python3
"""Generate voxen_codepoints.h — a C11 (std=c11) codepoint dictionary built from
the 8 language files text_<language>.txt in github.com/JosiahJack/Voxen/tree/master/Data.

Usage: python3 gen_voxen_codepoints.py [path/to/Voxen/Data]
Output: voxen_codepoints.h next to this script.
"""
import sys, os, unicodedata
from datetime import date

LANGS = [  # (repo suffix, language name, ISO code, bitmask)
    ("deutsch",   "German",     "DE", 1 << 0),
    ("english",   "English",    "EN", 1 << 1),
    ("espanol",   "Spanish",    "ES", 1 << 2),
    ("francais",  "French",     "FR", 1 << 3),
    ("italiano",  "Italian",    "IT", 1 << 4),
    ("nihongo",   "Japanese",   "JA", 1 << 5),
    ("portugues", "Portuguese", "PT", 1 << 6),
    ("russkiy",   "Russian",    "RU", 1 << 7),
]

data_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "Voxen", "Data")
out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "voxen_codepoints.h")

per_lang, totals = {}, {}
for suffix, name, code, bit in LANGS:
    path = os.path.join(data_dir, f"text_{suffix}.txt")
    with open(path, encoding="utf-16-le") as f:
        s = f.read()
    cps = {ord(c) for c in s}
    cps.discard(0xFEFF)  # UTF-16 BOM artifact at file start, not text content
    per_lang[suffix] = cps
    totals[suffix] = len(s)

union = sorted(set().union(*per_lang.values()))
count = len(union)


def glyph(cp: int) -> str:
    """Comment-safe display form of the character."""
    if cp == 0x0A:
        return r"\n"
    if cp == 0x09:
        return r"\t"
    ch = chr(cp)
    if not ch.isprintable():
        return f"\\x{cp:02X}"
    return ch  # single quoted char; '*' and '/' are individually safe in comments


def name_of(cp: int) -> str:
    if cp == 0x0A:
        return "LINE FEED (LF)"
    if cp == 0x09:
        return "CHARACTER TABULATION"
    return unicodedata.name(chr(cp), f"<U+{cp:04X}>")


def lang_comment(cp: int) -> str:
    used = " ".join(code for suffix, _, code, bit in LANGS if cp in per_lang[suffix])
    return used


lines = []
w = lines.append
w("/*")
w(" * voxen_codepoints.h")
w(" *")
w(" * Unique Unicode codepoint dictionary generated from the 8 localization")
w(" * files of the Voxen project (github.com/JosiahJack/Voxen), directory")
w(" * Data/, commit as of " + date.today().isoformat() + ":")
w(" *")
for suffix, name, code, bit in LANGS:
    w(f" *   text_{suffix}.txt{' ' * (11 - len(suffix))} ({name}, {len(per_lang[suffix])} unique codepoints)")
w(" *")
w(f" * All files are UTF-16 LE with a byte-order mark. The U+FEFF BOM is an")
w(f" * encoding artifact, not text content, and is therefore excluded.")
w(" *")
w(f" * Total unique codepoints across all 8 files: {count}")
w(" *")
w(" * The main array is sorted ascending with no duplicates, so it can be")
w(" * searched directly with voxen_codepoint_index() (binary search) below.")
w(" * A parallel array gives, for each codepoint, a bitmask of the languages")
w(" * that use it (see the VOXEN_LANG_* flags).")
w(" *")
w(" * Standard: ISO/IEC 9899:2011 (C11), '-std=c11'.")
w(" *   - uses <uchar.h> char32_t (introduced in C11)")
w(" *   - uses 'static inline' functions (proper 'inline' in C11)")
w(" *   - comment glyphs are UTF-8; array values are plain ASCII hex")
w(" *")
w(" * Generated by gen_voxen_codepoints.py — do not edit by hand.")
w(" */")
w("")
w("#ifndef VOXEN_CODEPOINTS_H")
w("#define VOXEN_CODEPOINTS_H")
w("")
w("#include <uchar.h>   /* char32_t   (C11) */")
w("#include <stddef.h>  /* size_t           */")
w("#include <stdint.h>  /* uint8_t          */")
w("")
w("#ifdef __cplusplus")
w('extern "C" {')
w("#endif")
w("")
w("/* ------------------------------------------------------------------ */")
w("/* Language bit flags — voxen_codepoint_langs[i] mask values           */")
w("/* ------------------------------------------------------------------ */")
w("")
for suffix, name, code, bit in LANGS:
    w(f"#define VOXEN_LANG_{''.join(p.upper() for p in suffix)} 0x{bit:02X}u /* {name:<11s} text_{suffix}.txt */")
w("#define VOXEN_LANG_ALL 0xFFu")
w("")
w("/* Number of unique codepoints (array elements) in the dictionary. */")
w(f"#define VOXEN_CODEPOINT_COUNT {count}")
w("")
w("/* ------------------------------------------------------------------ */")
w("/* Unique codepoints, sorted ascending, no duplicates.                */")
w("/* ------------------------------------------------------------------ */")
w("")
w("static const char32_t voxen_codepoints[VOXEN_CODEPOINT_COUNT] = {")
for i, cp in enumerate(union):
    comma = "," if i < count - 1 else " "
    w(f"    0x{cp:04X}{comma} /* U+{cp:04X} '{glyph(cp)}' {name_of(cp)} [{lang_comment(cp)}] */")
w("};")
w("")
w("/* ------------------------------------------------------------------ */")
w("/* Parallel array: for codepoint voxen_codepoints[i], a bitmask of     */")
w("/* the languages that use it (VOXEN_LANG_* flags).                     */")
w("/* ------------------------------------------------------------------ */")
w("")
w("static const uint8_t voxen_codepoint_langs[VOXEN_CODEPOINT_COUNT] = {")
for i, cp in enumerate(union):
    mask = 0
    for suffix, _, _, bit in LANGS:
        if cp in per_lang[suffix]:
            mask |= bit
    comma = "," if i < count - 1 else " "
    w(f"    0x{mask:02X}{comma} /* U+{cp:04X} '{glyph(cp)}' */")
w("};")
w("")
w("/* ------------------------------------------------------------------ */")
w("/* Dictionary lookup                                                   */")
w("/* ------------------------------------------------------------------ */")
w("")
w("/* Binary search: returns the index of 'cp' in voxen_codepoints,")
w(" * or (size_t)-1 if the codepoint does not occur in any Voxen language file. */")
w("static inline size_t voxen_codepoint_index(char32_t cp)")
w("{")
w("    size_t lo = 0, hi = VOXEN_CODEPOINT_COUNT;")
w("    while (lo < hi) {")
w("        size_t mid = lo + (hi - lo) / 2;")
w("        if (voxen_codepoints[mid] < cp)")
w("            lo = mid + 1;")
w("        else")
w("            hi = mid;")
w("    }")
w("    if (lo < VOXEN_CODEPOINT_COUNT && voxen_codepoints[lo] == cp)")
w("        return lo;")
w("    return (size_t)-1;")
w("}")
w("")
w("/* Returns nonzero if 'cp' occurs in at least one language file. */")
w("static inline int voxen_has_codepoint(char32_t cp)")
w("{")
w("    return voxen_codepoint_index(cp) != (size_t)-1;")
w("}")
w("")
w("/* Returns the VOXEN_LANG_* bitmask of languages using 'cp',")
w(" * or 0 if the codepoint is unknown. */")
w("static inline uint8_t voxen_codepoint_langs_of(char32_t cp)")
w("{")
w("    size_t i = voxen_codepoint_index(cp);")
w("    return i == (size_t)-1 ? 0u : voxen_codepoint_langs[i];")
w("}")
w("")
w("#ifdef __cplusplus")
w("} /* extern \"C\" */")
w("#endif")
w("")
w("#endif /* VOXEN_CODEPOINTS_H */")

with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"wrote {out_path}: {count} unique codepoints")
for suffix, _, code, _ in LANGS:
    print(f"  {code} text_{suffix}.txt: {len(per_lang[suffix]):4d} unique")
